---
title: "Orange Dot 6.0 - Regional Microdata"
# output: html_document
output:
  word_document:
    reference_docx: "styles.docx"
    toc: true
    toc_depth: 3
---
```{css, echo=FALSE}
.main-container.container-fluid {
  max-width: none;
  margin-left: auto;
  margin-right: auto;
  padding: 0 4.167%;
}

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

knitr::opts_template$set(fullwidth_table = list(
  fig.width = 6, fig.height = 4,
  fig.retina = 2, out.width = '100%'
),
fullwidth_bar = list(
  fig.width = 6, fig.height = 5,
  fig.retina = 2, out.width = '100%'
),
fullwidth_map = list(
  fig.width=9, fig.height=9,
  fig.retina = 2, out.width = '100%'
))

# Load packages ----
library(tidyverse)
library(scales)
library(readxl)
library(stringr)
library(ggthemes)
library(rcartocolor)
library(patchwork)
library(gt)
library(ggpol)
library(ggrepel)

# Palettes ----
pal_five <- c("#DE8A5A", "#EDBB8A", "#F6EDBD","#B4C8A8", "#70A494")
pal_six <- c("#CA562C", "#DE8A5A", "#EDBB8A", "#F6EDBD","#B4C8A8", "#70A494")
orange_dot <- "#CA562C"
green_dot <- "#B4C8A8"
grey_dot <-  "#b2b8be"
blue_dot <- "#3B8EA5"
  
# geography
geography_label <- "Thomas Jefferson Planning District"
# citations
acs_pums <- "Data Source: ACS Public Use Microdata Sample (PUMS), 2018-2022; U.S. Census Bureau."


```

```{r race_by_percent_2, fig.width = 9.5, fig.height = 6, fig.retina = 2}
# fam_by_race_2 <- read_csv("../microdata/data/families_by_race.csv")
# 
# fam_by_race_group_total <- fam_by_race_2 %>% 
#   group_by(hhldr_race_ethn) %>% 
#   summarise(group_total = sum(count)) %>% 
#   ungroup()
# 
# fam_by_race_by_group_totals <- fam_by_race_2 %>% 
#   left_join(fam_by_race_group_total) %>% 
#   select(-percent) %>% 
#   mutate(count_round = round(count, -2),
#          group_total_round = round(group_total, -2),
#     percent_of_group_total = round(count_round/group_total_round *100, 0)) %>% 
#   mutate(
#     race_ethn = case_when(hhldr_race_ethn %in% c("Hispanic", "Black", "White") ~ hhldr_race_ethn,
#                           .default = "All Other Groups"),
#     race_ethn = factor(race_ethn, levels = c("All Other Groups", "Hispanic", "Black", "White"), labels = c("All Other Groups", "Hispanic Families", "Black Families", "White Families")),
#          below_ess_finc = factor(below_ess_finc, levels = c("Yes", "No"),
#                                  labels = c("Income Below Self-Sufficiency Standard", "Income Above Self-Sufficiency Standard")))
# 
# fam_by_race_by_group_totals %>% 
#   filter(hhldr_race_ethn %in% c("White", "Black", "Hispanic")) %>% 
#   ggplot(aes(x = percent_of_group_total, y = race_ethn, group = race_ethn, fill = below_ess_finc)) +
#   geom_bar(stat = "identity", position = position_dodge2(width = 0.8, preserve = "single")) +
#   geom_text(aes(label = paste0(scales::percent(percent_of_group_total / 100, accuracy = 1), " (",
#                         scales::comma(count_round), " families)")),
#             position = position_dodge2(width = 0.8, preserve = "single"),
#             vjust = 0.5,
#             hjust = -0.05,
#             size = 5) +
#   scale_y_discrete(name = "") +
#   scale_x_continuous(name = "",
#                      limits = c(0,100),
#                      breaks = seq(0, 100, by = 25),
#                      label= label_percent(scale = 1),
#                      expand = expansion(mult = c(0, 0.18)),
#                      sec.axis = dup_axis()) +
#   scale_fill_manual(values = c(orange_dot, green_dot)) +
#   labs(title = "Race/Ethnicity of Families Earning Below and Above the Self-Sufficiency Standard",
#        subtitle = geography_label,
#        caption = acs_pums) +
#   theme_minimal() +
#   theme(legend.title=element_blank(),
#         legend.position = "top",
#         legend.location = "plot",
#         legend.justification="center",
#         legend.text = element_text(size = 13),
#           panel.grid.major.y = element_blank(),
#           axis.ticks = element_blank(),
#           panel.grid.minor = element_blank(),
#           plot.title.position= "plot",
#           plot.caption.position = "plot",
#         axis.text.y = element_text(color = "black", size = 14),
#         text = element_text(size = 14),
#         axis.text.x = element_text(size=14),
#         plot.title = element_text(size = 18),
#         plot.caption = element_text(size = 12))
```


```{r race_by_percent, fig.width = 9.5, fig.height = 6, fig.retina = 2}
fam_by_race <- read_csv("../microdata/data/families_by_race.csv") 

fam_by_ess_totals <- fam_by_race %>% 
  group_by(below_ess_finc) %>% 
  summarise(sss_group_total = sum(count)) %>% 
  ungroup()

fam_by_race_rounded<- fam_by_race %>%
  left_join(fam_by_ess_totals) %>% 
  mutate(count_rounded = round(count, -2),
         sss_group_tot_rounded = round(sss_group_total, -2),
         percent_rounded = round(count_rounded/sss_group_tot_rounded *100, 0),
    race_ethn = case_when(hhldr_race_ethn %in% c("Hispanic", "Black", "White") ~ hhldr_race_ethn,
                          .default = "All Other Groups"),
    race_ethn = factor(race_ethn, levels = c("White", "Black", "Hispanic", "All Other Groups"), labels = c("White\nFamilies", "Black\nFamilies", "Hispanic\nFamilies", "All Other Groups")),
         label_text = paste0(scales::percent(percent_rounded / 100, accuracy = 1), "\n(",
                        scales::comma(count_rounded), " families)"),
         below_ess_finc = factor(below_ess_finc, levels = c("Yes", "No"),
                                 labels = c("Income Below Self-Sufficiency Standard", "Income Above Self-Sufficiency Standard"))
    )

fam_by_race_rounded %>% 
  filter(hhldr_race_ethn %in% c("White", "Black", "Hispanic")) %>% 
  ggplot(aes(x = percent, y = race_ethn, group = race_ethn, fill = below_ess_finc)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = label_text),
            vjust = -0.35,
            hjust = 0.5,
            size = 4.5) +
  scale_y_discrete(name = "") +
  scale_x_continuous(name = "",
                     limits = c(0,100),
                     breaks = seq(0, 100, by = 25),
                     label= label_percent(scale = 1)) +
  scale_fill_manual(values = c(orange_dot, green_dot)) +
  coord_flip() +
  facet_wrap(~ below_ess_finc, scales = "free") +
  labs(title = "Race/Ethnicity of Families Earning Below and Above the Self-Sufficiency Standard",
       subtitle = geography_label,
       caption = paste0("Note: Not all groups are included here.\n", acs_pums)) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "none",
        # legend.location = "plot",
        # legend.justification="center",
        # legend.text = element_text(size = 13),
          panel.grid.major.x = element_blank(),
          axis.ticks = element_blank(),
          panel.grid.minor = element_blank(),
          plot.title.position= "plot",
          plot.caption.position = "plot",
        strip.text = element_text(size = rel(1.15),
                                  # face = "bold",
                                  color = "black"),
        # axis.text.y = element_text(color = "black", size = 14),
        text = element_text(size = 14),
        axis.text.x = element_text(size=14),
        plot.title = element_text(size = 18),
        plot.caption = element_text(size = 12))
```


```{r age_butterfly_percent, fig.width = 10.5, fig.height=6, fig.retina = 2}
fam_by_age <- read_csv("../microdata/data/families_by_age.csv") %>% 
  left_join(fam_by_ess_totals) %>% 
  mutate(count_rounded = round(count, -2),
         sss_group_tot_rounded = round(sss_group_total, -2),
         percent_rounded = round(count_rounded/sss_group_tot_rounded *100, 0)) %>% 
  mutate(hhldrage_bin = factor(hhldrage_bin, levels = c("65 and over", "55 to 64", "45 to 54", "35 to 44", "25 to 34", "Under 25")),
         below_ess_finc = factor(below_ess_finc, levels = c("Yes", "No"),
                                 labels = c("Income Below Self-Sufficiency Standard", "Income Above Self-Sufficiency Standard")))

dummy_age_per = tibble(y = c(-50, 0, 0, 50),
                    below_ess_finc = c("Income Above Self-Sufficiency Standard", "Income Above Self-Sufficiency Standard",
                                       "Income Below Self-Sufficiency Standard", "Income Below Self-Sufficiency Standard"))
    
dat_ess_per <- fam_by_age %>% 
    group_by(percent_rounded, below_ess_finc) %>%
    mutate(y = ifelse(below_ess_finc == "Income Above Self-Sufficiency Standard", -percent, percent),
           label_text = case_when(
           below_ess_finc == "Income Below Self-Sufficiency Standard" ~ paste0(percent_rounded, "%\n(", prettyNum(count_rounded, big.mark=",", preserve.width="none"), " families)"),
           below_ess_finc == "Income Above Self-Sufficiency Standard" ~ paste0(percent_rounded, "%\n(", prettyNum(count_rounded, big.mark=",", preserve.width="none"), " families)"))) %>%
    ungroup()

ggplot() +
  geom_bar(data = dat_ess_per,
           mapping = aes(y = y,
                         x = hhldrage_bin,
                         fill = below_ess_finc),
           stat = "identity",
           width = 0.8) +
  geom_blank(data = dummy_age_per,
             mapping = aes(y = y)) +
  geom_text(data = dat_ess_per,
            mapping = aes(x = hhldrage_bin,
                          y = case_when(below_ess_finc == "Income Above Self-Sufficiency Standard" ~  y-1.2,
                                        below_ess_finc == "Income Below Self-Sufficiency Standard" ~  y+1.2),
                          hjust = case_when(below_ess_finc == "Income Above Self-Sufficiency Standard" ~  1,
                                        below_ess_finc == "Income Below Self-Sufficiency Standard" ~  0),
                          label = label_text),
            size = 4.5
            ) +
  scale_x_discrete(name = "") +
  scale_y_continuous(expand = expansion(mult = c(0, 0)),
                     name = "Percent of Families") +
  scale_fill_manual(values = c(orange_dot, green_dot)) +  
  facet_share(~ below_ess_finc,
              dir = "h",
              scales = "free",
              reverse_num = TRUE) +
  coord_flip(clip = "off") +
  theme_light() +
  labs(title = "Age of Householder for Families Earning Below and Above the Self-Sufficiency Standard",
       subtitle = geography_label,
       caption = acs_pums) +
  theme(legend.position = "none",
        panel.grid.minor.x = element_blank(),
        panel.border = element_blank(),
        strip.text = element_text(size = rel(1.15),
                                  # face = "bold",
                                  color = "black"),
    strip.background = element_rect(fill = "white", colour = "black", size = 0),
    plot.title.position= "plot",
          plot.caption.position = "plot",
        axis.text.y = element_text(hjust = 0.5, color = "black", size = 14),
        text = element_text(size = 14),
        axis.title.x = element_text(size=13),
        plot.title = element_text(size = 18),
        plot.caption = element_text(size = 12))

```


```{r tenure-stacked, fig.width=9.5, fig.height=5, fig.retina = 2}
fam_by_tenure <- read_csv("../microdata/data/families_by_tenure.csv") %>% 
  mutate(label_text = case_when(
    below_ess_finc == "No" ~ paste0(prettyNum(count, big.mark=",", preserve.width="none"), " (", round(percent, 0), "% of families above SSS)"),
    below_ess_finc == "Yes" ~ paste0(prettyNum(count, big.mark=",", preserve.width="none"), " (", round(percent, 0), "% of families below SSS)")),
         below_ess_finc = factor(below_ess_finc, levels = c("No", "Yes"),
                                 labels = c("Income Above\nSelf-Sufficiency Standard", "Income Below\nSelf-Sufficiency Standard")),
    own_rent = factor(own_rent, levels = c("Own", "Rent"), labels = c("Homeowners", "Renters")))

fam_by_tenure %>% 
  ggplot(aes(x = percent, y = below_ess_finc, group=below_ess_finc, fill = own_rent)) +
  geom_bar(stat = "identity") +
  geom_label_repel(aes(label = case_when(
           own_rent == "Homeowners" ~ paste0(round(percent, 0), "% are Homeowners\n(", prettyNum(count, big.mark=",", preserve.width="none"), " families)"),
           own_rent == "Renters" ~ paste0(round(percent, 0), "% are Renters\n(", prettyNum(count, big.mark=",", preserve.width="none"), " families)"))),
                  size = 4.5, fontface = "bold", show.legend = FALSE,
                  min.segment.length = Inf,
                  position = position_stack(vjust = 0.35),
           vjust = 0.5,
           hjust = -0.025,
                  box.padding = 0.01,
                  # force_pull = 100,
                  # direction = "x",
                  color = "white") +
  scale_x_continuous(limits = c(0, 100),
                     labels = label_percent(scale = 1), 
                     name = "Percent of Families",
                     sec.axis = dup_axis()) + 
  scale_y_discrete(name = "") +
  scale_fill_manual(values = c(grey_dot, blue_dot)) +
  labs(title = "Housing Status for Families Earning Below and Above the Self-Sufficiency Standard",
       subtitle = geography_label,
       caption = acs_pums) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        # legend.location = "plot",
        legend.justification="center",
        legend.text = element_text(size = 13),
          panel.grid.major.y = element_blank(),
          axis.ticks = element_blank(),
          panel.grid.minor = element_blank(),
          plot.title.position= "plot",
          plot.caption.position = "plot",
        axis.text.y = element_text(hjust = 0.5, color = "black", size = 14),
        text = element_text(size = 14),
        axis.title.x = element_text(size=12),
        plot.title = element_text(size = 18),
        plot.caption = element_text(size = 12))
```


```{r burden, fig.width=9.5, fig.height=5, fig.retina = 2}
fam_by_burden <- read_csv("../microdata/data/families_by_burden.csv") %>% 
  mutate(label_text = case_when(
    below_ess_finc == "No" ~ paste0(prettyNum(count, big.mark=",", preserve.width="none"), " (", round(percent, 0), "% of families above SSS)"),
    below_ess_finc == "Yes" ~ paste0(prettyNum(count, big.mark=",", preserve.width="none"), " (", round(percent, 0), "% of families below SSS)")),
         below_ess_finc = factor(below_ess_finc, levels = c("No", "Yes"),
                                 labels = c("Income Above\nSelf-Sufficiency Standard", "Income Below\nSelf-Sufficiency Standard")))

fam_by_burden %>% 
  ggplot(aes(x = percent, y = below_ess_finc, group=below_ess_finc, fill = factor(shelter_burden, levels = c("Not Burdened", "Burdened", "Severely Burdened"), labels = c("Not Burdened\nLess than 30% household income", "Burdened\n30% to 49% household income", "Severely Burdened\nOver 50% household income")))) +
  geom_bar(stat = "identity") +
  # geom_text(aes(label = case_when(
  #          shelter_burden == "Not Burdened" ~ paste0(round(percent, 0), "% are Not Burdened\n(", prettyNum(count, big.mark=",", preserve.width="none"), " families)"),
  #          shelter_burden == "Burdened" ~ paste0(round(percent, 0), "% are Burdened\n(", prettyNum(count, big.mark=",", preserve.width="none"), " families)"),
  #          shelter_burden == "Severely Burdened" ~ paste0(round(percent, 0), "% are Severely Burdened\n(", prettyNum(count, big.mark=",", preserve.width="none"), " families)"))),
  #           position = position_stack(vjust = 0.5),
  #           vjust = 0.5,
  #           # hjust = -0.025,
  #           size = 3) +
  geom_label_repel(aes(label = case_when(
           shelter_burden == "Not Burdened" ~ paste0(round(percent, 0), "% Not Burdened\n(", prettyNum(count, big.mark=",", preserve.width="none"), " families)"),
           shelter_burden == "Burdened" ~ paste0(round(percent, 0), "% Burdened\n(", prettyNum(count, big.mark=",", preserve.width="none"), " families)"),
           shelter_burden == "Severely Burdened" ~ paste0(round(percent, 0), "% Severely Burdened\n(", prettyNum(count, big.mark=",", preserve.width="none"), " families)"))),
                  size = 4, fontface = "bold", show.legend = FALSE,
                  min.segment.length = Inf,
                  position = position_stack(vjust = 0.25),
           # vjust = 0.5,
           hjust = -0.025,
                  box.padding = 0.01,
                  # force_pull = 100,
                  # direction = "x",
                  color = "white",
                   seed = 123) +
  scale_x_continuous(limits = c(0, 100),
                     labels = label_percent(scale = 1), 
                     name = "Percent of Families",
                     sec.axis = dup_axis(),
                     expand = expansion(mult = c(0, .35))) + 
  scale_y_discrete(name = "") +
  scale_fill_manual(values = c("#B4C8A8", "#DE8A5A", "#CA562C")) +
  labs(title = "Housing Burden for Families Earning Below and Above the Self-Sufficiency Standard",
       subtitle = geography_label,
       caption = acs_pums) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        legend.location = "plot",
        legend.justification="center",
        legend.text = element_text(size = 13),
          panel.grid.major.y = element_blank(),
          axis.ticks = element_blank(),
          panel.grid.minor = element_blank(),
          plot.title.position= "plot",
          plot.caption.position = "plot",
        axis.text.y = element_text(hjust = 0.5, color = "black", size = 14),
        text = element_text(size = 14),
        axis.title.x = element_text(size=12),
        plot.title = element_text(size = 18),
        plot.caption = element_text(size = 12))

```


```{r disability, fig.width=9.5, fig.height=5, fig.retina = 2}
people_by_disability <- read_csv("../microdata/data/people_by_disability.csv")

people_by_disability %>% 
  mutate(label = paste0(scales::percent(percent / 100, accuracy = 1), "\n(",
                        scales::comma(count), ")"),
         disability_status = factor(dis, levels = c(1,2), labels = c("With a disability","No disability")),
         below_ess_finc = factor(below_ess_finc, levels = c("No", "Yes"),
                                 labels = c("Income Above\nSelf-Sufficiency Standard", "Income Below\nSelf-Sufficiency Standard"))) %>% 
  arrange(disability_status) %>% 
  ggplot(aes(x = percent, y = below_ess_finc, group = below_ess_finc, fill = disability_status, label = label)) +
  geom_bar(stat = "identity", color = "white") +
  geom_label_repel(aes(label = label),
                   size = 4.5, fontface = "bold", show.legend = FALSE,
                   # min.segment.length = Inf,
                   position = position_stack(vjust = 0.5),
                   # box.padding = 0.1,
                   # force_pull = 100,
                   direction = "x",
                   color = "white",
                   seed = 123) +
  # geom_text(position = position_dodge2(width = 0.5, preserve = "single"), 
  #           vjust = 0.5,
  #           hjust = -0.2,
  #           size = 3) +
  scale_x_continuous(labels = scales::percent_format(scale = 1),
                     limits = c(0,100),
                     sec.axis = dup_axis(),
                     name = "") +
  scale_y_discrete(name = "") +
  scale_fill_manual(values = c("No disability"=grey_dot,"With a disability"=blue_dot)) +
  labs(title = "Disability Status for People Earning Below and Above the Self-Sufficiency Standard",
       subtitle = geography_label,
       caption = acs_pums) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        legend.text = element_text(size = 13),
        panel.grid.major.y = element_blank(),
        plot.title.position= "plot",
          plot.caption.position = "plot",
        axis.text.y = element_text(hjust = 0.5, color = "black", size = 14),
        text = element_text(size = 14),
        axis.title.x = element_text(size=12),
        plot.title = element_text(size = 18),
        plot.caption = element_text(size = 12))

```

```{r workers_by_hours, fig.width = 9.5, fig.height = 6, fig.retina = 2}
workers_by_hours <- read_csv("../microdata/data/workers_by_hours.csv") %>% 
  mutate(
    hours_bin = factor(hours_bin, levels = c("Unemployed", "Less than 20", "20 to 29", "30 to 34", "35 to 39", "40 or more"), labels = c("Unemployed", "Less than 20 hours", "20 to 29 hours", "30 to 34 hours", "35 to 39 hours", "40 or more hours")),
         label_text = case_when(
           below_ess_finc == "Yes" ~ paste0(prettyNum(count, big.mark=",", preserve.width="none"), " (", round(percent, 0), "%)"),
           below_ess_finc == "No" ~ paste0(prettyNum(count, big.mark=",", preserve.width="none"), " (", round(percent, 0), "%)")),
         below_ess_finc = factor(below_ess_finc, levels = c("Yes", "No"),
                                 labels = c("Income Below Self-Sufficiency Standard", "Income Above Self-Sufficiency Standard")))

workers_by_hours %>% 
  filter(below_ess_finc == "Income Below Self-Sufficiency Standard") %>% 
  ggplot(aes(x = count, y = hours_bin)) +
  geom_bar(stat = "identity", fill = blue_dot) +
  geom_text(aes(label = label_text),
            vjust = 0.5,
            hjust = -0.1,
            size = 5) +
  scale_y_discrete(name = "") +
  scale_x_continuous(name = "Number of Workers",
                     breaks = seq(0, 12000, by = 2500),
                     label=comma,
                     expand = expansion(mult = c(0, .2))) +
  labs(title = "Weekly Hours Worked for Workers Earning Below the Self-Sufficiency Standard",
       subtitle = geography_label,
       caption = acs_pums) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        legend.text = element_text(size = 12),
        # legend.location = "plot",
        legend.justification="center",
          # panel.grid.major.y = element_blank(),
          axis.ticks = element_blank(),
          panel.grid.minor = element_blank(),
          plot.title.position= "plot",
          plot.caption.position = "plot",
        axis.text.y = element_text(color = "black", size = 14),
        text = element_text(size = 14),
        axis.text.x = element_text(size=14),
        plot.title = element_text(size = 18),
        plot.caption = element_text(size = 12))

```

```{r family_income, fig.width = 10, fig.height = 6, fig.retina = 2}

family_income <- read_csv("../microdata/data/families_below_ess_by_incomes.csv")

family_income %>%
  ggplot(aes(x = count, y = income_bins, fill = income_bins)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = paste0(prettyNum(count, big.mark=",", preserve.width="none"), " (", round(percent, 0), "%)")),
            vjust = 0.5,
            hjust = -0.1,
            size = 5) +
  scale_y_discrete(name = "") +
  scale_x_continuous(name = "Number of Families",
                     breaks = seq(0, 4000, by = 1000),
                     label=comma,
                     expand = expansion(mult = c(0, .19))
                     ) +
  scale_fill_manual(values = c("#EDBB8A", "#EDBB8A","#DE8A5A", "#DE8A5A", "#DE8A5A", "#B4C8A8"))+
  labs(title = "Annual Incomes for Families Earning Below the Self-Sufficiency Standard",
       subtitle = geography_label,
       caption = acs_pums) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "none",
        # legend.location = "plot",
        legend.justification="center",
        legend.text = element_text(size = 12),
          # panel.grid.major.y = element_blank(),
          axis.ticks = element_blank(),
          panel.grid.minor = element_blank(),
          plot.title.position= "plot",
          plot.caption.position = "plot",
        axis.text.y = element_text(color = "black", size = 14),
        text = element_text(size = 14),
        axis.text.x = element_text(size=14),
        plot.title = element_text(size = 18),
        plot.caption = element_text(size = 12))
```


```{r workers_by_medianwages, fig.width = 10, fig.height = 6, fig.retina = 2}
workers_by_medianwages <- read_csv("../microdata/data/workers_by_medianwages.csv") %>% 
   mutate(
    median_wage_bin_label = factor(median_wage_bin_label, levels = c("25610-37760", "37860-48320", "48340-60600", "60640-86950", "88050-238990"), labels = c("$25,610 - $37,760", "$37,860 - $48,320", "$48,340 - $60,600", "$60,640 - $86,950", "$88,050 - $238,990")),
         label_text = case_when(
           below_ess_finc == "Yes" ~ paste0(prettyNum(count, big.mark=",", preserve.width="none"), " (", round(percent, 0), "%)"),
           below_ess_finc == "No" ~ paste0(prettyNum(count, big.mark=",", preserve.width="none"), " (", round(percent, 0), "%)")),
         below_ess_finc = factor(below_ess_finc, levels = c("Yes", "No"),
                                 labels = c("Income Below Self-Sufficiency Standard", "Income Above Self-Sufficiency Standard")))

workers_by_medianwages %>% 
  filter(below_ess_finc == "Income Below Self-Sufficiency Standard") %>% 
  ggplot(aes(x = count, y = median_wage_bin_label, fill = median_wage_bin_label)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = label_text),
            vjust = 0.5,
            hjust = -0.1,
            size = 5) +
  scale_y_discrete(name = "") +
  scale_x_continuous(name = "Number of Workers",
                     breaks = seq(0, 12000, by = 1500),
                     label=comma,
                     expand = expansion(mult = c(0, .19))) +
  scale_fill_manual(values = c("#DE8A5A", "#EDBB8A", "#F6EDBD","#B4C8A8", "#70A494"))+
  labs(title = "Annual Median Wage for Workers Earning Below the Self-Sufficiency Standard",
       subtitle = geography_label,
       caption = "Bureau of Labor Statistics, U.S. Department of Labor. Occupational Employment and Wage Statistics, 2023.") +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "none",
        # legend.location = "plot",
        legend.justification="center",
        legend.text = element_text(size = 12),
          # panel.grid.major.y = element_blank(),
          axis.ticks = element_blank(),
          panel.grid.minor = element_blank(),
          plot.title.position= "plot",
          plot.caption.position = "plot",
        axis.text.y = element_text(color = "black", size = 14),
        text = element_text(size = 14),
        axis.text.x = element_text(size=14),
        plot.title = element_text(size = 18),
        plot.caption = element_text(size = 12))

```

```{r occupations_by_wagebin, fig.width = 6, fig.height = 10,  fig.retina = 2}
occupations_by_wagebin <- read_csv("../microdata/data/occupations_by_wagebin.csv")

occupations_filtered <- occupations_by_wagebin %>% 
  # filter(employment_per_1_000_jobs > 8) %>% 
  filter(occupation %in% c("Fast Food and Counter Workers", "Cashiers", "Home Health and Personal Care Aides", "Childcare Workers",
                           "Customer Service Representatives", "Construction Laborers", "Maintenance and Repair Workers, General", 
                           "Emergency Medical Technicians", "Nursing Assistants", 
                           "Healthcare Support Workers, All Other", "Medical Assistants",
                           "Bus Drivers, Transit and Intercity", "Dental Assistants", "Bus Drivers, School",
                           "Automotive Service Technicians and Mechanics", "Heavy and Tractor-Trailer Truck Drivers",
                           "Carpenters", "Production, Planning, and Expediting Clerks",
                           "Graphic Designers", "Plumbers, Pipefitters, and Steamfitters",
                           "Electricians", "Medical Records Specialists", "Police and Sheriff's Patrol Officers",
                           "Clinical Laboratory Technologists and Technicians", "Elementary School Teachers, Except Special Education",
                           "Secondary School Teachers, Except Special and Career/Technical Education",
                           "Office and Administrative Support Workers, All Other", "Registered Nurses", 
                           "Radiologic Technologists and Technicians", "Computer User Support Specialists", 
                           "Accountants and Auditors", "Nurse Practitioners",
                           "General and Operations Managers", "Construction Managers", "Dental Hygienists", 
                           "Heating, Air Conditioning, and Refrigeration Mechanics and Installers", 
                           "Electrical and Electronic Engineering Technologists and Technicians", 
                           "Licensed Practical and Licensed Vocational Nurses", "Surgical Technologists")) %>% 
#   filter(occupation %in% c("Fast Food and Counter Workers", "Cashiers", "Home Health and Personal Care Aides",
#                            "Customer Service Representatives", "Construction Laborers", "Light Truck Drivers", "Maintenance and Repair Workers, General", "Elementary School Teachers, Except Special Education
# ", "Electricians", "Medical Records Specialists", "Office and Administrative Support Workers, All Other", "Registered Nurses", "Radiologic Technologists and Technicians", "Computer User Support Specialists", "General and Operations Managers", "Construction Managers", "Dental Hygienists")) %>% 
  mutate(median_wage_bin_label = factor(median_wage_bin_label, levels = c("25610-37760", "37860-48320", "48340-60600", "60640-86950", "88050-238990"), labels = c("$25,610 - $37,760", "$37,860 - $48,320", "$48,340 - $60,600", "$60,640 - $86,950", "$88,050 - $238,990")),
         job_group = case_when(soc_group_num == "11" ~ "Management",
soc_group_num == "13" ~ "Business and Financial Operations",
soc_group_num == "15" ~ "Computer and Mathematical",
soc_group_num == "17" ~ "Architecture and Engineering",
soc_group_num == "19" ~ "Life, Physical, and Social Science",
soc_group_num == "21" ~ "Community and Social Service",
soc_group_num == "23" ~ "Legal",
soc_group_num == "25" ~ "Educational Instruction and Library",
soc_group_num == "27" ~ "Arts, Design, Entertainment, Sports, and Media",
soc_group_num == "29" ~ "Healthcare Practitioners and Technical",
soc_group_num == "31" ~ "Healthcare Support",
soc_group_num == "33" ~ "Protective Service",
soc_group_num == "35" ~ "Food Preparation and Serving Related",
soc_group_num == "37" ~ "Building and Grounds Cleaning and Maintenance",
soc_group_num == "39" ~ "Personal Care and Service",
soc_group_num == "41" ~ "Sales and Related",
soc_group_num == "43" ~ "Office and Administrative Support",
soc_group_num == "45" ~ "Farming, Fishing, and Forestry",
soc_group_num == "47" ~ "Construction and Extraction",
soc_group_num == "49" ~ "Installation, Maintenance, and Repair",
soc_group_num == "51" ~ "Production",
soc_group_num == "53" ~ "Transportation and Material Moving"
))

occupations_filtered %>%
  mutate(employment_per_1_000_jobs = employment_per_1_000_jobs/100,
         color = "") %>% 
  select(c(occupation, annual_median_wage_2, color, employment_per_1_000_jobs, job_group, median_wage_bin)) %>%
  gt() %>% 
  # tab_row_group(label = "Occupations Earning $88,050 - $238,990",
  #               rows = 14:16) %>%
  # tab_row_group(label = "Occupations Earning $60,640 - $86,950",
  #               rows = 11:13) %>%
  # tab_row_group(label = "Occupations Earning $48,340 - $60,600",
  #               rows = 8:10) %>%
  # tab_row_group(label = "Occupations Earning $37,860 - $48,320",
  #               rows = 5:7) %>%
  # tab_row_group(label = "Occupations Earning $25,610 - $37,760",
  #               rows = 1:4) %>%
  data_color(
    columns = median_wage_bin,
    target_columns = color,
    direction = "column",
    # method = "numeric",
    # domain = c(20000,120000),
    palette = c("#DE8A5A", "#EDBB8A", "#F6EDBD","#B4C8A8", "#70A494"),
    # na_color = "white"
  ) %>% 
  fmt_currency(
    columns = 2,
    currency = currency(
      html = "&#36;",
      default = "$"
    ),
    decimals = 2
  ) %>% 
  fmt_percent(
    columns = employment_per_1_000_jobs,
    decimals = 0
  ) %>% 
  cols_hide(columns = c(median_wage_bin)) %>% 
  cols_label(
    occupation = "Occupation",
    annual_median_wage_2 = "Annual Median Wage",
        color = "",
    employment_per_1_000_jobs = "Employment Rate",
    median_wage_bin = "",
    job_group = "Occupation Group"
  ) %>% 
  tab_style(
    style = cell_text(align = "center", v_align = "middle"),
    locations = list(cells_column_labels(2:4), cells_body(2:4))
  ) %>% 
  tab_footnote(
    footnote = "See appendix for more occupations by annual median wage",
    locations = cells_title(groups = "title")
  ) %>% 
  tab_footnote(
    footnote = "The annual median wage is the boundary between the highest and lowest paid workers in a given occupation. Half of the workers in a given occupation earn more than the median wage, and half the workers earn less than the median wage.",
    locations = cells_column_labels(columns = annual_median_wage_2)
  ) %>% 
  tab_footnote(
    footnote = "Employment rate is the number of jobs (employment) in the given occupation per 1,000 jobs in the Charlottesville Metro Area",
    locations = cells_column_labels(columns = employment_per_1_000_jobs)
  ) %>% 
  tab_footnote(
    footnote = "Major occupation groups defined by the Standard Occupational Classification (SOC) system, used by Federal statistical agencies to classify workers and jobs into occupational categories for the purpose of collecting, calculating, analyzing, or disseminating data.",
    locations = cells_column_labels(columns = job_group)
  ) %>% 
  tab_header(
    title = "Selection of Occupations by Annual Median Wage Earned in the Charlottesville Metro Area"
  ) %>% 
  tab_source_note(
    source_note = "Data Source: U.S. Bureau of Labor Statistics, Occupational Employment and Wage Statistics; May 2023"
  )
```


## Appendix
```{r occupations_median_age_by_job_group}
occupations_median_age_by_job_group <- read_csv("../microdata/data/occupation_wages_catchallcategories.csv")

occupations_median_age_by_job_group %>% 
  arrange(annual_median_wage_2) %>% 
  select(occupation, hourly_mean_wage, annual_mean_wage_2, hourly_median_wage, annual_median_wage_2, employment_per_1_000_jobs, median_wage_bin) %>% 
  mutate(employment_per_1_000_jobs = employment_per_1_000_jobs/100,
         color = "") %>% 
  select(c(occupation, hourly_mean_wage, annual_mean_wage_2, hourly_median_wage, annual_median_wage_2, color, employment_per_1_000_jobs, median_wage_bin)) %>%
  gt() %>% 
  data_color(
    columns = median_wage_bin,
    target_columns = color,
    direction = "column",
    palette = c("#DE8A5A", "#EDBB8A", "#F6EDBD","#B4C8A8", "#70A494"),
  ) %>% 
  fmt_currency(
    columns = 2:5,
    currency = currency(
      html = "&#36;",
      default = "$"
    ),
    decimals = 2
  ) %>% 
  fmt_percent(
    columns = employment_per_1_000_jobs,
    decimals = 0
  ) %>% 
  cols_hide(columns = c(median_wage_bin)) %>% 
  cols_label(
    occupation = "Occupation Group",
    hourly_mean_wage = "Hourly Mean (Average) Wage", 
    annual_mean_wage_2 = "Annual Mean (Average) Wage", 
    hourly_median_wage = "Hourly Median Wage",
    annual_median_wage_2 = "Annual Median Wage",
        color = "",
    employment_per_1_000_jobs = "Employment Rate",
    median_wage_bin = ""
  ) %>% 
  tab_style(
    style = cell_text(align = "center", v_align = "middle"),
    locations = list(cells_column_labels(2:4), cells_body(2:4))
  ) %>%
  tab_footnote(
    footnote = "The annual median wage is the boundary between the highest and lowest paid workers in a given occupation. Half of the workers in a given occupation earn more than the median wage, and half the workers earn less than the median wage.",
    locations = cells_column_labels(columns = annual_median_wage_2)
  ) %>% 
  tab_footnote(
    footnote = "Employment rate is the number of jobs (employment) in the given occupation per 1,000 jobs in the Charlottesville Metro Area",
    locations = cells_column_labels(columns = employment_per_1_000_jobs)
  ) %>% 
  tab_footnote(
    footnote = "Major occupation groups defined by the Standard Occupational Classification (SOC) system, used by Federal statistical agencies to classify workers and jobs into occupational categories for the purpose of collecting, calculating, analyzing, or disseminating data.",
    locations = cells_column_labels(columns = occupation)
  ) %>% 
  tab_header(
    title = "Occupation Groups by Mean (Average) and Median Wages Earned in the Charlottesville Metro Area"
  ) %>% 
  tab_source_note(
    source_note = "Data Source: U.S. Bureau of Labor Statistics, Occupational Employment and Wage Statistics; May 2023"
  )
  

```


```{r occupations_by_wagebin_appendix, fig.width = 6, fig.height = 10,  fig.retina = 2}

occupation_appendix <- occupations_by_wagebin %>%
  filter(employment_per_1_000_jobs > 1) %>%
  mutate(median_wage_bin_label = factor(median_wage_bin_label, levels = c("25610-37760", "37860-48320", "48340-60600", "60640-86950", "88050-238990"), labels = c("$25,610 - $37,760", "$37,860 - $48,320", "$48,340 - $60,600", "$60,640 - $86,950", "$88,050 - $238,990")),
         employment_per_1_000_jobs = round(employment_per_1_000_jobs,1),
         job_group = case_when(soc_group_num == "11" ~ "Management",
soc_group_num == "13" ~ "Business and Financial Operations",
soc_group_num == "15" ~ "Computer and Mathematical",
soc_group_num == "17" ~ "Architecture and Engineering",
soc_group_num == "19" ~ "Life, Physical, and Social Science",
soc_group_num == "21" ~ "Community and Social Service",
soc_group_num == "23" ~ "Legal",
soc_group_num == "25" ~ "Educational Instruction and Library",
soc_group_num == "27" ~ "Arts, Design, Entertainment, Sports, and Media",
soc_group_num == "29" ~ "Healthcare Practitioners and Technical",
soc_group_num == "31" ~ "Healthcare Support",
soc_group_num == "33" ~ "Protective Service",
soc_group_num == "35" ~ "Food Preparation and Serving Related",
soc_group_num == "37" ~ "Building and Grounds Cleaning and Maintenance",
soc_group_num == "39" ~ "Personal Care and Service",
soc_group_num == "41" ~ "Sales and Related",
soc_group_num == "43" ~ "Office and Administrative Support",
soc_group_num == "45" ~ "Farming, Fishing, and Forestry",
soc_group_num == "47" ~ "Construction and Extraction",
soc_group_num == "49" ~ "Installation, Maintenance, and Repair",
soc_group_num == "51" ~ "Production",
soc_group_num == "53" ~ "Transportation and Material Moving"
))

# write.xlsx(occupation_appendix, "OccupationsByWageBin.xlsx")

occupation_appendix %>%
  mutate(employment_per_1_000_jobs = employment_per_1_000_jobs/100,
         color = "") %>% 
  select(c(occupation, annual_median_wage_2, color, employment_per_1_000_jobs, job_group, median_wage_bin)) %>%
  gt() %>% 
  data_color(
    columns = median_wage_bin,
    target_columns = color,
    direction = "column",
    # method = "numeric",
    # domain = c(20000,120000),
    palette = c("#DE8A5A", "#EDBB8A", "#F6EDBD","#B4C8A8", "#70A494"),
    # na_color = "white"
  ) %>% 
  fmt_currency(
    columns = 2,
    currency = currency(
      html = "&#36;",
      default = "$"
    ),
    decimals = 2
  ) %>% 
  fmt_percent(
    columns = employment_per_1_000_jobs,
    decimals = 0
  ) %>% 
  cols_hide(columns = c(median_wage_bin)) %>% 
  cols_label(
    occupation = "Occupation",
    annual_median_wage_2 = "Annual Median Wage",
        color = "",
    employment_per_1_000_jobs = "Employment Rate",
    median_wage_bin = "",
    job_group = "Occupation Group"
  ) %>% 
  tab_style(
    style = cell_text(align = "center", v_align = "middle"),
    locations = list(cells_column_labels(2:4), cells_body(2:4))
  ) %>%
  tab_footnote(
    footnote = "The annual median wage is the boundary between the highest and lowest paid workers in a given occupation. Half of the workers in a given occupation earn more than the median wage, and half the workers earn less than the median wage.",
    locations = cells_column_labels(columns = annual_median_wage_2)
  ) %>% 
  tab_footnote(
    footnote = "Employment rate is the number of jobs (employment) in the given occupation per 1,000 jobs in the Charlottesville Metro Area",
    locations = cells_column_labels(columns = employment_per_1_000_jobs)
  ) %>% 
  tab_footnote(
    footnote = "Major occupation groups defined by the Standard Occupational Classification (SOC) system, used by Federal statistical agencies to classify workers and jobs into occupational categories for the purpose of collecting, calculating, analyzing, or disseminating data.",
    locations = cells_column_labels(columns = job_group)
  ) %>% 
  tab_header(
    title = "Occupations by Annual Median Wage Earned in the Charlottesville Metro Area"
  ) %>% 
  tab_source_note(
    source_note = "Data Source: U.S. Bureau of Labor Statistics, Occupational Employment and Wage Statistics; May 2023"
  )
```

```{r family_income_summary, fig.width = 7.25, fig.height = 6, fig.retina = 2}

family_income_summary <- read_csv("../microdata/data/families_below_ess_by_incomes.csv") %>% 
  mutate(group = case_when(income_bins %in% c("$0 to $9,999","$10,000 to $19,999") ~ "Less than $20K",
                           income_bins %in% c("$20,000 to $29,999","$30,000 to $39,999", "$40,000 to $49,999") ~ "Between $20K - $50K",
                           income_bins == "$50,000+" ~ "$50,000+"))

family_income_summary %>%
  group_by(group) %>% 
  summarise(count = sum(count),
            percent = sum(percent)) %>% 
  ungroup() %>% 
  mutate(group = factor(group, levels = c("Less than $20K", "Between $20K - $50K", "$50,000+"))) %>% 
  ggplot(aes(x = count, y = group, fill = group)) +
  geom_bar(stat = "identity") +
  geom_text(aes(label = paste0(prettyNum(round(count, -1), big.mark=",", preserve.width="none"), " families\n(", round(percent, 0), "%)")),
            vjust = -0.35,
            # hjust = -0.1,
            size = 5) +
  scale_y_discrete(name = "") +
  scale_x_continuous(name = "Number of Families",
                     breaks = seq(0, 10000, by = 1000),
                     label=comma,
                     expand = expansion(mult = c(0, .16))
                     ) +
  scale_fill_manual(values = c("#EDBB8A", "#DE8A5A", "#B4C8A8"))+
  coord_flip()+
  labs(
    # title = "Annual Incomes for Families Earning Below the Self-Sufficiency Standard",
       # subtitle = geography_label,
       caption = acs_pums) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "none",
        # legend.location = "plot",
        legend.justification="center",
        legend.text = element_text(size = 12),
          panel.grid.major = element_blank(),
          axis.ticks = element_blank(),
        axis.title.y = element_blank(),
                axis.text.y.left = element_blank(),

          panel.grid.minor = element_blank(),
          plot.title.position= "plot",
          plot.caption.position = "plot",
        axis.text.y = element_text(color = "black", size = 14),
        text = element_text(size = 14),
        axis.text.x = element_text(size=16),
        plot.title = element_text(size = 20),
        plot.caption = element_text(size = 12))
```