---
title: "Orange Dot 6.0 - Locality Profiles"
output: html_document
# output: word_document
# output:
#   bookdown::word_document2
---
```{css, echo=FALSE}
.main-container.container-fluid {
  max-width: none;
  margin-left: auto;
  margin-right: auto;
  padding: 0 4.167%;
}

```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

knitr::opts_template$set(fullwidth_bar = list(
  fig.width = 6, fig.height = 5,
  fig.retina = 2, out.width = '100%'
),
fullwidth_map = list(
  fig.width=9, fig.height=9,
  fig.retina = 2, out.width = '100%'
))

# Load packages ----
library(tidyverse)
library(tidycensus)
library(scales)
library(RColorBrewer)
library(ggspatial)
library(tigris)
library(readxl)
library(stringr)
library(sf)
library(ggthemes)
library(rcartocolor)
library(patchwork)
library(gt)

# Tract geometries ----
county_codes <- c("003", "540", "065", "079", "109", "125", "029")
tract_geo <- tracts(state = "VA", county = county_codes)

# Map palettes ----
pal_inc <- carto_pal(7, "Geyser")
# "#008080" "#70A494" "#B4C8A8" "#F6EDBD" "#EDBB8A" "#DE8A5A" "#CA562C"
# pal_inc <- c("#EE6400","#F37903","#F78C05","#FCA108","#E7AD1B","#ABB046","#6FB272","#33B59D","#2DB0AC","#4CA7A9")

pal_ssw <- carto_pal(7, "RedOr")
# "#F6D2A9" "#F5B78E" "#F19C7C" "#EA8171" "#DD686C" "#CA5268" "#B13F64"
# pal_ssw <- c("#F6D2A9", "#F5B78E", "#F19C7C", "#EA8171", "#DD686C")

# Pull in data ----
# County self sufficiency tables ----
selfsuff_county <- read_csv("../data/self_suff_county_2021.csv")

selfsuff_mean_monthly <- selfsuff_county %>% 
  select(county, ends_with("_mean")) %>% 
  select(-c(emergency_savings_mean, hourly_self_sufficiency_wage_mean, annual_self_sufficiency_wage_mean)) %>% 
  rename(self_sufficiency_wage_mean = monthly_self_sufficiency_wage_mean) %>% 
  pivot_longer(housing_costs_mean:self_sufficiency_wage_mean, values_to = "Monthly")

selfsuff_mean_annual <- selfsuff_county %>% 
  select(county, ends_with("_mean")) %>% 
  relocate(annual_self_sufficiency_wage_mean, .after = last_col()) %>% 
  select(-c(emergency_savings_mean, hourly_self_sufficiency_wage_mean, monthly_self_sufficiency_wage_mean)) %>%
  mutate(across(housing_costs_mean:child_tax_credit_mean, function(x) x*12)) %>% 
  rename(self_sufficiency_wage_mean = annual_self_sufficiency_wage_mean) %>% 
  pivot_longer(housing_costs_mean:self_sufficiency_wage_mean, values_to = "Annual")

# selfsuff_mean_weekly <- selfsuff_county %>% 
#   select(county, ends_with("_mean")) %>% 
#   select(-c(emergency_savings_mean, annual_self_sufficiency_wage_mean)) %>%
#   mutate(across(housing_costs_mean:child_tax_credit_mean, function(x) x/4),
#          weekly_self_sufficiency_wage_mean = monthly_self_sufficiency_wage_mean/4,
#          wwekly_sum = rowSums(across(housing_costs_mean:child_tax_credit_mean), na.rm =TRUE),
#          monthly_by_hr = monthly_self_sufficiency_wage_mean/176,
#          weekly_by_hr = hourly_self_sufficiency_wage_mean * 44) 

# Join tables
selfsuff_table <- selfsuff_mean_monthly %>% 
  left_join(selfsuff_mean_annual) %>% 
  mutate(name = str_remove(name, "_mean")) %>% 
  mutate(name = str_to_title(str_replace_all(name, "_", " ")),
         county = str_to_title(county))

ssw_table_title <- "Average Expenses and Self-Sufficiency Wages for Families in "

# Families with income below 35k, between 35k-self sufficiency wage & above ssw ----
fam_ssw <- read_csv("../data/faminc_ssw_race_county_2022.csv")

fam_ssw_dat <- fam_ssw %>% 
  select(-c(estimate,moe)) %>% 
  pivot_wider(names_from = ssw_group, values_from = percent) %>% 
  pivot_longer(above_ssw:below_thirtyfive) %>% 
  mutate(number = round(total_families*(value/100), 0),
         group = factor(group,
                       levels = c("Black", "Hispanic", "White, Not Hispanic", "All Families"),
                       labels = c("Black Families", "Hispanic Families", "White Families", "All Families")),
         name = factor(name,
                       levels = c("above_ssw", "below_ssw", "below_thirtyfive"),
                       labels = c("Income above SSW", "Income below SSW & above $35K", "Income below $35K")),
  text = case_when(value >= 20 ~ paste0(round(value, 0), "%\n(", prettyNum(number, big.mark=",", preserve.width="none"), ")"),
                   value < 20 & value >= 1 ~ paste0(round(value, 0), "% (", prettyNum(number, big.mark=",", preserve.width="none"), ")"),
                   value < 1 ~ ""),
  locality_label = paste0(str_to_title(str_remove(locality, ", Virginia")), " (Annual Self-Sufficieny Standard ", self_suff_wage, ")"))

fam_ssw_dat <- fam_ssw_dat[order(fam_ssw_dat$name),]

fam_ssw_pal <- c("#B4C8A8", "#DE8A5A", "#CA562C")
fam_ssw_title <- "Families Earning Below and Above the Self-Sufficiency Standard"

# Total Families and Total Below SSW by county ----
fam_ssw_totals <- fam_ssw_dat %>% 
  filter(str_detect(name, "Income below")) %>% 
  group_by(locality, group) %>% 
  summarise(total_families = first(total_families),
            below_ssw_num = sum(number),
            below_ssw_per = sum(round(value))) %>% 
  mutate(locality = str_to_title(str_remove(locality, ", Virginia")))
  
# Income distribution by race/ethnicity by county ----
faminc_race <- read_csv("../data/faminc_race_county_2022.csv") 

faminc_race <- faminc_race %>% 
  filter(inc_band != "Total Families") %>% 
  mutate(inc_band_group = case_when(str_detect(variable, "_002|_003|_004|_005|_006|_007") ~ "Earning below $35K",
                               str_detect(variable, "_008|_009|_010|_011") ~ "Earning $35K-$59.9K",
                               str_detect(variable, "_012|_013") ~ "Earning $60K-$100K",
                               str_detect(variable, "_014|_015|_016|_017") ~ "Earning above $100K"),
         inc_rank = case_when(str_detect(variable, "_002|_003|_004|_005|_006|_007") ~ 1,
                               str_detect(variable, "_008|_009|_010|_011") ~ 2,
                               str_detect(variable, "_012|_013") ~ 3,
                               str_detect(variable, "_014|_015|_016|_017") ~ 4))

faminc_data <- faminc_race %>% 
  group_by(GEOID, locality, year, group, inc_band_group, inc_rank) %>% 
  summarise(estimate = sum(estimate),
            moe = moe_sum(moe = moe, estimate = estimate),
            total_families = first(total_families)) %>% 
  ungroup() %>% 
  mutate(percent = estimate/total_families *100,
         group = factor(group,
                         levels = c("Black", "Hispanic", "White, Not Hispanic", "All Families"),
                         labels = c("Black Families", "Hispanic Families", "White Families", "All Families")),
           inc_band_group = factor(inc_band_group,
                              levels = c("Earning above $100K",  "Earning $60K-$100K", "Earning $35K-$59.9K", "Earning below $35K")),
    text = case_when(percent >= 1 ~ paste0(round(percent, 0), "%\n(", prettyNum(estimate, big.mark=",", preserve.width="none"), ")"),
                     percent < 1 ~ ""),
  locality_label = str_to_title(str_remove(locality, ", Virginia")))

faminc_pal <- c("#E4EAF1", "#B4C8A8", "#DE8A5A", "#CA562C")
faminc_title <- "Distribution of Family Income"

# Median family income by county ----
med_faminc_county <- read_csv("../data/med_faminc_county_2022.csv") %>%
  mutate(GEOID = as.character(GEOID),
         estimate = round(estimate, 0),
         locality = str_to_title(str_remove(locality, ", Virginia")))

# Median family income by tract ----
med_faminc_tract <- read_csv("../data/med_faminc_tract_2022.csv") %>%
  mutate(GEOID = as.character(GEOID),
         estimate = round(estimate, -2),
         locality = str_to_title(locality))

med_faminc_tract <- med_faminc_tract %>%
  left_join(tract_geo, by = "GEOID") %>% 
  st_as_sf()

min_inc <- min(med_faminc_tract$estimate, na.rm = TRUE)
max_inc <- max(med_faminc_tract$estimate, na.rm = TRUE)

# Below Self Sufficiency Standard, by tract ----
ssw_tract <- read_csv("../data/faminc_ssw_tract_2022.csv") %>%
  filter(ssw_group == "below") %>%
  mutate(GEOID = as.character(GEOID),
         percent = round(percent,0),
         locality = str_to_title(locality))

ssw_tract <- ssw_tract %>%
  left_join(tract_geo, by = "GEOID") %>% 
  st_as_sf()

min_ssw <- min(ssw_tract$percent, na.rm = TRUE)
max_ssw <- max(ssw_tract$percent, na.rm = TRUE)


# Sources ----
source_acs <- "Data Source: American Community Survey, 2022"
uw_sss_source <- "Data Source: The Self-Sufficiency Standard for Virginia, 2021; The Center for Women’s Welfare, University of Washington"

```

## Albemarle County
```{r}
# Set name
local_name <- "Albemarle County"

<<locality_summary>>

```

```{r locality_summary, echo=FALSE}
# Calculate summary values ----
# Total Families and Total Below SSW
total_fam <- fam_ssw_totals %>%
  filter(group == "All Families" & locality == local_name)

total <- prettyNum(total_fam$total_families, big.mark=",", preserve.width="none")
locality_name <- total_fam$locality
below_ssw <- prettyNum(total_fam$below_ssw_num, big.mark=",", preserve.width="none")
below_ssw_per <- percent(total_fam$below_ssw_per, scale = 1, accuracy = 1)

# Black families
black_fam <- fam_ssw_totals %>%
  filter(group == "Black Families" & locality == local_name)
below_ssw_black <- prettyNum(black_fam$below_ssw_num, big.mark=",", preserve.width="none")
below_ssw_per_black <- black_fam$below_ssw_per

# Hispanic families
his_fam <- fam_ssw_totals %>%
  filter(group == "Hispanic Families" & locality == local_name)
below_ssw_his <- prettyNum(his_fam$below_ssw_num, big.mark=",", preserve.width="none")
below_ssw_per_his <- his_fam$below_ssw_per

# White families
white_fam <- fam_ssw_totals %>%
  filter(group == "White Families" & locality == local_name)
below_ssw_white <- prettyNum(white_fam$below_ssw_num, big.mark=",", preserve.width="none")
below_ssw_per_white <- white_fam$below_ssw_per

# SSW table
selfsuff_table_data <- selfsuff_table %>% 
  filter(county == local_name)

ssw_annual<- selfsuff_table_data %>% 
  filter(name == "Self Sufficiency Wage")
ssw_annual<- paste0("$", prettyNum(ssw_annual$Annual, big.mark=",", preserve.width="none"))

# Median Family income
med_faminc <- med_faminc_county %>% 
  filter(locality == local_name)
med_faminc<-paste0("$", prettyNum(med_faminc$estimate, big.mark=",", preserve.width="none"))

med_faminc_low <- med_faminc_tract %>% 
  filter(locality == local_name) %>% 
  filter(estimate == min(estimate, na.rm = TRUE))
med_faminc_low_est <- paste0("$", prettyNum(med_faminc_low$estimate, big.mark=",", preserve.width="none"))
med_faminc_low_name <- med_faminc_low$tractnames

med_faminc_high <- med_faminc_tract %>% 
  filter(locality == local_name) %>% 
  filter(estimate == max(estimate, na.rm = TRUE))
med_faminc_high_est <- paste0("$", prettyNum(med_faminc_high$estimate, big.mark=",", preserve.width="none"))
med_faminc_high_name <- med_faminc_high$tractnames

# SSW by tract
ssw_tract_high <- ssw_tract %>% 
  filter(locality == local_name) %>% 
  filter(percent == max(percent, na.rm = TRUE))
ssw_tract_high_per <- unique(ssw_tract_high$percent)
ssw_tract_high_name <- paste(ssw_tract_high$tractnames, collapse = " and ")

ssw_tract_low <- ssw_tract %>% 
  filter(locality == local_name) %>% 
  filter(percent == min(percent, na.rm = TRUE))
ssw_tract_low_per <- unique(ssw_tract_low$percent)
ssw_tract_low_name <- paste(ssw_tract_low$tractnames, collapse = " and ")

# Section summary texts ----

section_summary_w_hisp <- paste0("
<p>There are ", total, " families living in ", locality_name, ". Of these, ", below_ssw," (", below_ssw_per,") do not earn enough to provide for their family’s basic needs.</p>
<p>", locality_name, " at a glance:</p>
<ul>
<li><p>The Self-Sufficiency Standard for an average family in ", locality_name, " is an annual income of ", ssw_annual, ". This is the income working families need to meet their basic necessities. These include: housing, child care, food, transportation, health care, miscellaneous expenses (clothing, telephone, household items), and taxes (minus federal and state tax credits).</p></li>

<li><p>Approximately ", below_ssw, " families, or ", below_ssw_per, " of families, in ", locality_name, " earn below the Self-Sufficiency Standard.</p></li>

<li><p>The percent of Black families earning below the Self-Sufficiency Standard is ", percent(below_ssw_per_black, scale = 1, accuracy = 1), ". The percent of Hispanic families earning below the Self-Sufficiency Standard is ", percent(below_ssw_per_his, scale = 1, accuracy = 1), ". These are ", percent(below_ssw_per_black-below_ssw_per_white, scale = 1, accuracy = 1), " and ", percent(below_ssw_per_his-below_ssw_per_white, scale = 1, accuracy = 1), " higher than the percent of white families earning below the Self-Sufficiency Standard (", percent(below_ssw_per_white, scale = 1, accuracy = 1), ").</p></li>

<li><p>The median family income for ", locality_name, " is ", med_faminc, ". The tract with the lowest median family income is ", med_faminc_low_name, " at ", med_faminc_low_est, ". The tract with the highest median family income is ", med_faminc_high_name, " at ", med_faminc_high_est, ".</p></li>

<li><p>The tract with the highest percent of families with income below the Self-Sufficiency Standard is ", ssw_tract_high_name, " with ", percent(ssw_tract_high_per, scale = 1, accuracy = 1), " of families. The tract with the lowest percent of families earning below the Self-Sufficiency Standard is ", ssw_tract_low_name, " with ", percent(ssw_tract_low_per, scale = 1, accuracy = 1), " of families. That is a difference of ", percent(ssw_tract_high_per-ssw_tract_low_per, scale = 1, accuracy = 1), ".</p></li>
</ul>
")

section_summary <- paste0("
<p>There are ", total, " families living in ", locality_name, ". Of these, ", below_ssw," (", below_ssw_per,") do not earn enough to provide for their family’s basic needs.</p>
<p>", locality_name, " at a glance:</p>
<ul>
<li><p>The Self-Sufficiency Standard for an average family in ", locality_name, " is an annual income of ", ssw_annual, ". This is the income working families need to meet their basic necessities. These include: housing, child care, food, transportation, health care, miscellaneous expenses (clothing, telephone, household items), and taxes (minus federal and state tax credits).</p></li>

<li><p>Approximately ", below_ssw, " families, or ", below_ssw_per, " of families, in ", locality_name, " earn below the Self-Sufficiency Standard.</p></li>

<li><p>The percent of Black families earning below the Self-Sufficiency Standard is ", percent(below_ssw_per_black, scale = 1, accuracy = 1), ". This is ", percent(below_ssw_per_black-below_ssw_per_white, scale = 1, accuracy = 1), " higher than the percent of white families earning below the Self-Sufficiency Standard (", percent(below_ssw_per_white, scale = 1, accuracy = 1), ").</p></li>

<li><p>The median family income for ", locality_name, " is ", med_faminc, ". The tract with the lowest median family income is ", med_faminc_low_name, " at ", med_faminc_low_est, ". The tract with the highest median family income is ", med_faminc_high_name, " at ", med_faminc_high_est, ".</p></li>

<li><p>The tract with the highest percent of families with income below the Self-Sufficiency Standard is ", ssw_tract_high_name, " with ", percent(ssw_tract_high_per, scale = 1, accuracy = 1), " of families. The tract with the lowest percent of families earning below the Self-Sufficiency Standard is ", ssw_tract_low_name, " with ", percent(ssw_tract_low_per, scale = 1, accuracy = 1), " of families. That is a difference of ", percent(ssw_tract_high_per-ssw_tract_low_per, scale = 1, accuracy = 1), ".</p></li>
</ul>
")


```

<!-- There are `r total` families living in `r locality_name`. Of these, `r below_ssw` (`r below_ssw_per`) do not earn enough to provide for their family's basic needs. -->

<!-- `r locality_name` at a glance: -->

<!-- - The Self-Sufficiency Standard for an average family in `r locality_name` is an annual income of `r ssw_annual`. This is the income working families need to meet their basic necessities. These include: housing, child care, food, transportation, health care, miscellaneous expenses (clothing, telephone, household items), and taxes (minus federal and state tax credits). -->

<!-- - Approximately `r below_ssw` families, or `r below_ssw_per` of families, in `r locality_name` earn below the Self-Sufficiency Standard. -->

<!-- - The percent of Black families earning below the Self-Sufficiency Standard is `r percent(below_ssw_per_black, scale = 1, accuracy = 1)`. The percent of Hispanic families earning below the Self-Sufficiency Standard is `r percent(below_ssw_per_his, scale = 1, accuracy = 1)`. These are `r percent(below_ssw_per_black-below_ssw_per_white, scale = 1, accuracy = 1)` and `r percent(below_ssw_per_his-below_ssw_per_white, scale = 1, accuracy = 1)` higher than the percent of white families earning below the Self-Sufficiency Standard (`r percent(below_ssw_per_white, scale = 1, accuracy = 1)`). -->

<!-- - The median family income for `r locality_name` is `r med_faminc`. The tract with the lowest median family income is `r med_faminc_low_name` at `r med_faminc_low_est`. The tract with the highest median family income is `r med_faminc_high_name` at `r med_faminc_high_est`. -->

<!-- - The tract with the highest percent of families with income below the Self-Sufficiency Standard is `r ssw_tract_high_name` with `r percent(ssw_tract_high_per, scale = 1, accuracy = 1)` of families. The tract with the lowest percent of families earning below the Self-Sufficiency Standard is `r ssw_tract_low_name` with `r percent(ssw_tract_low_per, scale = 1, accuracy = 1)` of families. That is a difference of `r percent(ssw_tract_high_per-ssw_tract_low_per, scale = 1, accuracy = 1)`. -->


`r section_summary_w_hisp`

```{r ssw_table_alb, echo=FALSE}
# County self sufficiency table ----
selfsuff_table_alb <- selfsuff_table %>% 
  filter(county == "Albemarle County")

selfsuff_table_alb %>% 
  select(-c(county)) %>% 
  gt(rowname_col = "name") %>% 
  # tab_row_group(label = "Deductions",
  #               rows = 8:10) %>% 
  # tab_row_group(label = "Costs",
  #               rows = 1:7) %>% 
  fmt_currency(
    columns = 2:3,
    currency = currency(
      html = "&#36;",
      default = "$"
    ),
    decimals = 2
  ) %>% 
  tab_style(
    style = list(
      cell_fill(color = "#F6D2A9"),
      cell_text(weight = "bold")
    ),
    locations = list(cells_body(rows = 11), cells_stub(rows = 11))
  ) %>% 
  tab_style(
    style = cell_text(align = "center", v_align = "middle"),
    locations = list(cells_column_labels(), cells_body())
  ) %>% 
  tab_style(
    style = cell_text(weight = "bold"),
    locations = list(cells_column_labels())
  ) %>% 
  tab_header(
    title = paste0(ssw_table_title, unique(selfsuff_table_alb$county))
  ) %>% 
  tab_source_note(
    source_note = uw_sss_source
  )
  
```


```{r, opts.label='fullwidth_bar'}
# Families with income below 35k, between 35k-self sufficiency wage & above ssw ----
# Families below and above SSW
fam_ssw_alb <- fam_ssw_dat %>% 
  filter(locality == "Albemarle County, Virginia")

fam_ssw_alb %>% 
  arrange(desc(name)) %>% 
  ggplot(aes(x = group, y = value, group = group, fill = name, 
             label = text)) +
  geom_bar(stat = "identity", color = "white") + 
  geom_text(size = 3, position = position_stack(vjust = 0.5), lineheight = 1) +
  scale_fill_manual(values = fam_ssw_pal) +
  scale_x_discrete(name = "") +
  scale_y_continuous(labels = label_percent(scale = 1),
                     name = "") +
  guides(fill = guide_legend(reverse = TRUE)) +
  labs(title = fam_ssw_title, 
       subtitle = unique(fam_ssw_alb$locality_label),
       caption = source_acs) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        panel.grid.major.x = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position= "plot",
        plot.caption.position = "plot")
```

```{r, echo=FALSE,fig.width=7, fig.height=5}
# # Income distribution by race/ethnicity by county ----
# faminc_alb <- faminc_data %>% 
#   filter(locality == "Albemarle County, Virginia")
# 
# faminc_alb %>% 
#   arrange(inc_rank) %>%
#   ggplot(aes(x = group, y = percent, group = group, fill = inc_band_group, 
#                label = text)) +
#   geom_bar(stat = "identity", color = "white") + 
#   geom_text(size = 3, position = position_stack(vjust = 0.5)) +
#   scale_fill_manual(values = faminc_pal) +
#   scale_x_discrete(name = "") +
#   scale_y_continuous(labels = label_percent(scale = 1),
#                      name = "") +
#   guides(fill = guide_legend(reverse = TRUE)) +
#   coord_flip() + 
#   labs(title = faminc_title, 
#        subtitle = unique(faminc_alb$locality_label),
#        caption = source_acs) +
#   theme_minimal() +
#   theme(legend.title=element_blank(),
#         legend.position = "top",
#         legend.location = "plot",
#         legend.justification="center",
#           panel.grid.major.x = element_blank(),
#           axis.ticks = element_blank(),
#           panel.grid.minor = element_blank(),
#           plot.title.position= "plot",
#           plot.caption.position = "plot")

```

```{r, opts.label='fullwidth_map'}
# Geospatial visualization: Albemarle ----
alb_inc_map <- med_faminc_tract %>%
  filter(locality == "Albemarle County") %>%
  mutate(text = paste0("$", prettyNum((round(estimate,-3)/1000), big.mark=",", preserve.width="none"), "K")) %>%
  ggplot() +
  annotation_map_tile(zoomin = 1, progress = "none", cachedir = "../data/tempdata/") +
  geom_sf(aes(fill = estimate), color = "white") +
  geom_sf_text(aes(label = text), size = 2.5, color = "black") +
  scale_fill_stepsn(colors = rev(pal_inc),
                    labels = scales::label_currency(scale = 1),
                    n.breaks = 7,
                    trans = "log",
                    limits = c(min_inc, max_inc),
                    guide = guide_colourbar(title = "Median Family Income",
                                            title.position = "top",
                                            direction = "vertical",
                                            theme = theme(legend.key.height  = unit(10, "lines"),
                                                          legend.key.width = unit(0.5, "lines"),
                                                          text = element_text(size = 10))
                                            )
                    )+
  labs(title = "Median Family Income by Tract",
      subtitle = unique(fam_ssw_alb$locality_label),
      caption = source_acs) +
  theme_map() +
  theme(legend.position="right")


alb_ssw_map <- ssw_tract %>%
  filter(locality == "Albemarle County") %>%
  mutate(text = paste0(round(percent,0), "%")) %>%
  ggplot() +
  annotation_map_tile(zoomin = 1, progress = "none", cachedir = "../data/tempdata/") +
  geom_sf(aes(fill = percent), color = "white") +
  geom_sf_text(aes(label = text), size = 2.5, color = "black") +
  scale_fill_stepsn(colors = pal_ssw,
                    labels = scales::label_percent(scale = 1),
                    breaks = c(5,7,15,20,40,60),
                    # nice.breaks = TRUE,
                    trans = "log",
                    limits = c(min_ssw, max_ssw),
                    guide = guide_colourbar(title = "Percent Below SSS",
                                            title.position = "top",
                                            direction = "vertical",
                                            theme = theme(legend.key.height  = unit(10, "lines"),
                                                          legend.key.width = unit(0.5, "lines"),
                                                          text = element_text(size = 10)) 
                                            )
                    )+
  labs(title = "Families with Income below Self Sufficiency Standard",
      subtitle = "Albemarle",
      caption = "") +
  theme_map()+
  theme(legend.position="right")

alb_inc_map 

alb_ssw_map
```

## Buckingham County
```{r, echo=FALSE}
# Set name
local_name <- "Buckingham County"

<<locality_summary>>

```

`r section_summary`

<!-- There are `r total` families living in `r locality_name`. Of these, `r below_ssw` (`r below_ssw_per`) do not earn enough to provide for their family's basic needs. -->

<!-- `r locality_name` at a glance: -->

<!-- - The Self-Sufficiency Standard for an average family in `r locality_name` is an annual income of `r ssw_annual`. This is the income working families need to meet their basic necessities. These include: housing, child care, food, transportation, health care, miscellaneous expenses (clothing, telephone, household items), and taxes (minus federal and state tax credits). -->

<!-- - Approximately `r below_ssw` families, or `r below_ssw_per` of families, in `r locality_name` earn below the Self-Sufficiency Standard. -->

<!-- - The percent of Black families earning below the Self-Sufficiency Standard is `r percent(below_ssw_per_black, scale = 1, accuracy = 1)`. This is `r percent(below_ssw_per_black-below_ssw_per_white, scale = 1, accuracy = 1)` higher than the percent of white families earning below the Self-Sufficiency Standard (`r percent(below_ssw_per_white, scale = 1, accuracy = 1)`). -->

<!-- - The median family income for `r locality_name` is `r med_faminc`. The tract with the lowest median family income is `r med_faminc_low_name` at `r med_faminc_low_est`. The tract with the highest median family income is `r med_faminc_high_name` at `r med_faminc_high_est`. -->

<!-- - The tract with the highest percent of families with income below the Self-Sufficiency Standard is `r ssw_tract_high_name` with `r percent(ssw_tract_high_per, scale = 1, accuracy = 1)` of families. The tract with the lowest percent of families earning below the Self-Sufficiency Standard is `r ssw_tract_low_name` with `r percent(ssw_tract_low_per, scale = 1, accuracy = 1)` of families. That is a difference of `r percent(ssw_tract_high_per-ssw_tract_low_per, scale = 1, accuracy = 1)`. -->

```{r ssw_table_buc}
# County self sufficiency table ----
selfsuff_table_buc <- selfsuff_table %>% 
  filter(county == "Buckingham County")

selfsuff_table_buc %>% 
  select(-c(county)) %>% 
  gt(rowname_col = "name") %>% 
  # tab_row_group(label = "Deductions",
  #               rows = 8:10) %>% 
  # tab_row_group(label = "Costs",
  #               rows = 1:7) %>% 
  fmt_currency(
    columns = 2:3,
    currency = currency(
      html = "&#36;",
      default = "$"
    ),
    decimals = 2
  ) %>% 
  tab_style(
    style = list(
      cell_fill(color = "#F6D2A9"),
      cell_text(weight = "bold")
    ),
    locations = list(cells_body(rows = 11), cells_stub(rows = 11))
  ) %>% 
  tab_style(
    style = cell_text(align = "center", v_align = "middle"),
    locations = list(cells_column_labels(), cells_body())
  ) %>% 
  tab_style(
    style = cell_text(weight = "bold"),
    locations = list(cells_column_labels())
  ) %>% 
  tab_header(
    title = paste0(ssw_table_title, str_to_title(unique(selfsuff_table_buc$county)))
  ) %>% 
  tab_source_note(
    source_note = uw_sss_source
  )
  
```

```{r, echo = FALSE,fig.width=6, fig.height=5}
# Families with income below 35k, between 35k-self sufficiency wage & above ssw ----
fam_ssw_buc <- fam_ssw_dat %>% 
  filter(locality == "Buckingham County, Virginia" & group != "Hispanic Families")

fam_ssw_buc %>% 
  arrange(desc(name)) %>% 
  ggplot(aes(x = group, y = value, group = group, fill = name, 
             label = text)) +
  geom_bar(stat = "identity", color = "white") + 
  geom_text(size = 3, position = position_stack(vjust = 0.5), lineheight = 1) +
  scale_fill_manual(values = fam_ssw_pal) +
  scale_x_discrete(name = "") +
  scale_y_continuous(labels = label_percent(scale = 1),
                     name = "") +
  guides(fill = guide_legend(reverse = TRUE)) +
  labs(title = fam_ssw_title, 
       subtitle = unique(fam_ssw_buc$locality_label),
       caption = source_acs) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        panel.grid.major.x = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position= "plot",
        plot.caption.position = "plot")
```

```{r, echo=FALSE,fig.width=6.5, fig.height=4}
# # Income distribution by race/ethnicity by county ----
# faminc_buc <- faminc_data %>% 
#   filter(locality == "Buckingham County, Virginia" & group != "Hispanic Families")
# 
# faminc_buc %>% 
#   arrange(inc_rank) %>%
#   ggplot(aes(x = group, y = percent, group = group, fill = inc_band_group, 
#                label = text)) +
#   geom_bar(stat = "identity", color = "white") + 
#   geom_text(size = 3, position = position_stack(vjust = 0.5)) +
#   scale_fill_manual(values = faminc_pal) +
#   scale_x_discrete(name = "") +
#   scale_y_continuous(labels = label_percent(scale = 1),
#                      name = "") +
#   guides(fill = guide_legend(reverse = TRUE)) +
#   coord_flip() + 
#   labs(title = faminc_title, 
#        subtitle = unique(faminc_buc$locality_label),
#        caption = source_acs) +
#   theme_minimal() +
#   theme(legend.title=element_blank(),
#         legend.position = "top",
#         legend.location = "plot",
#         legend.justification="center",
#           panel.grid.major.x = element_blank(),
#           axis.ticks = element_blank(),
#           panel.grid.minor = element_blank(),
#           plot.title.position= "plot",
#           plot.caption.position = "plot")

```

```{r, echo=FALSE, warning = FALSE, message = FALSE, fig.width=12, fig.height=6}
# Geospatial visualization: Buckingham ----
buc_inc_map <- med_faminc_tract %>%
  filter(locality == "Buckingham County") %>%
  mutate(text = paste0("$", prettyNum(estimate, big.mark=",", preserve.width="none"))) %>%
  ggplot() +
  annotation_map_tile(zoomin = 1, progress = "none", cachedir = "../data/tempdata/") +
  geom_sf(aes(fill = estimate), color = "white") +
  geom_sf_text(aes(label = text), size = 2.5, color = "black") +
  scale_fill_stepsn(colors = rev(pal_inc),
                    labels = scales::label_currency(scale = 1),
                    trans = "log",
                    n.breaks = 7,
                    limits = c(min_inc, max_inc),
                    guide = guide_colourbar(title = "Median Family Income",
                                            title.position = "top",
                                            direction = "vertical",
                                            theme = theme(legend.key.height  = unit(10, "lines"),
                                                          legend.key.width = unit(0.5, "lines"),
                                                          text = element_text(size = 10))
                                            )
                    )+
  labs(title = "Median Family Income by Tract",
      subtitle = "Buckingham County",
      caption = source_acs <- "Data Source: American Community Survey, 2022") +
  theme_map() +
  theme(legend.position="right")


buc_ssw_map <- ssw_tract %>%
  filter(locality == "Buckingham County") %>%
  filter(ssw_group == "below") %>%
  mutate(text = paste0(round(percent,0), "%")) %>%
  ggplot() +
  annotation_map_tile(zoomin = 1, progress = "none", cachedir = "../data/tempdata/") +
  geom_sf(aes(fill = percent), color = "white") +
  geom_sf_text(aes(label = text), size = 2.5, color = "black") +
  scale_fill_stepsn(colors = pal_ssw,
                    labels = scales::label_percent(scale = 1),
                    breaks = c(5,7,15,20,40,60),
                    trans = "log",
                    limits = c(min_ssw, max_ssw),
                    guide = guide_colourbar(title = "Percent Below SSS",
                                            title.position = "top",
                                            direction = "vertical",
                                            theme = theme(legend.key.height  = unit(10, "lines"),
                                                          legend.key.width = unit(0.5, "lines"),
                                                          text = element_text(size = 10)) 
                                            )
                    )+
  labs(title = "Families with Income below Self Sufficiency Standard",
      subtitle = "Buckingham County",
      caption = "") +
  theme_map()+
  theme(legend.position="right")

buc_inc_map 

buc_ssw_map
```

## City of Charlottesville
```{r, echo=FALSE}
# Set name
local_name <- "Charlottesville City"

<<locality_summary>>

```

`r section_summary_w_hisp`

```{r ssw_table_cville}
# County self sufficiency table ----
selfsuff_table_cville <- selfsuff_table %>% 
  filter(county == "Charlottesville City")

selfsuff_table_cville %>% 
  select(-c(county)) %>% 
  gt(rowname_col = "name") %>% 
  # tab_row_group(label = "Deductions",
  #               rows = 8:10) %>% 
  # tab_row_group(label = "Costs",
  #               rows = 1:7) %>% 
  fmt_currency(
    columns = 2:3,
    currency = currency(
      html = "&#36;",
      default = "$"
    ),
    decimals = 2
  ) %>% 
  tab_style(
    style = list(
      cell_fill(color = "#F6D2A9"),
      cell_text(weight = "bold")
    ),
    locations = list(cells_body(rows = 11), cells_stub(rows = 11))
  ) %>% 
  tab_style(
    style = cell_text(align = "center", v_align = "middle"),
    locations = list(cells_column_labels(), cells_body())
  ) %>% 
  tab_style(
    style = cell_text(weight = "bold"),
    locations = list(cells_column_labels())
  ) %>% 
  tab_header(
    title = paste0(ssw_table_title, str_to_title(unique(selfsuff_table_cville$county)))
  ) %>% 
  tab_source_note(
    source_note = uw_sss_source
  )
  
```

```{r, echo = FALSE,fig.width=6, fig.height=5}
# Families with income below 35k, between 35k-self sufficiency wage & above ssw ----
fam_ssw_cville <- fam_ssw_dat %>% 
  filter(locality == "Charlottesville city, Virginia")

fam_ssw_cville %>% 
  arrange(desc(name)) %>% 
  ggplot(aes(x = group, y = value, group = group, fill = name, 
             label = text)) +
  geom_bar(stat = "identity", color = "white") + 
  geom_text(size = 3, position = position_stack(vjust = 0.5), lineheight = 1) +
  scale_fill_manual(values = fam_ssw_pal) +
  scale_x_discrete(name = "") +
  scale_y_continuous(labels = label_percent(scale = 1),
                     name = "") +
  guides(fill = guide_legend(reverse = TRUE)) +
  labs(title = fam_ssw_title, 
       subtitle = unique(fam_ssw_cville$locality_label),
       caption = source_acs) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        panel.grid.major.x = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position= "plot",
        plot.caption.position = "plot")
```

```{r, echo=FALSE,fig.width=7, fig.height=5}
# # Income distribution by race/ethnicity by county ----
# faminc_cville <- faminc_data %>% 
#   filter(locality == "Charlottesville city, Virginia")
# 
# faminc_cville %>% 
#   arrange(inc_rank) %>%
#   ggplot(aes(x = group, y = percent, group = group, fill = inc_band_group, 
#                label = text)) +
#   geom_bar(stat = "identity", color = "white") + 
#   geom_text(size = 3, position = position_stack(vjust = 0.5)) +
#   scale_fill_manual(values = faminc_pal) +
#   scale_x_discrete(name = "") +
#   scale_y_continuous(labels = label_percent(scale = 1),
#                      name = "") +
#   guides(fill = guide_legend(reverse = TRUE)) +
#   coord_flip() + 
#   labs(title = faminc_title, 
#        subtitle = unique(faminc_cville$locality_label),
#        caption = source_acs) +
#   theme_minimal() +
#   theme(legend.title=element_blank(),
#         legend.position = "top",
#         legend.location = "plot",
#         legend.justification="center",
#           panel.grid.major.x = element_blank(),
#           axis.ticks = element_blank(),
#           panel.grid.minor = element_blank(),
#           plot.title.position= "plot",
#           plot.caption.position = "plot")

```

```{r, echo=FALSE, warning = FALSE, message = FALSE, fig.width=12, fig.height=6}

# Geospatial visualization: Charlottesville ----
cville_inc_map <- med_faminc_tract %>%
  filter(locality == "Charlottesville City") %>%
  mutate(text = case_when(is.na(estimate) ~ "",
                          .default = paste0("$", prettyNum(estimate, big.mark=",", preserve.width="none")))) %>%
  ggplot() +
  annotation_map_tile(zoomin = 1, progress = "none", cachedir = "../data/tempdata/") +
  geom_sf(aes(fill = estimate), color = "white") +
  geom_sf_text(aes(label = text), size = 2.5, color = "black") +
  scale_fill_stepsn(colors = rev(pal_inc),
                    labels = scales::label_currency(scale = 1),
                    trans = "log",
                    n.breaks = 7,
                    limits = c(min_inc, max_inc),
                    na.value = "grey70",
                    guide = guide_colourbar(title = "Median Family Income",
                                            title.position = "top",
                                            direction = "vertical",
                                            theme = theme(legend.key.height  = unit(10, "lines"),
                                                          legend.key.width = unit(0.5, "lines"),
                                                          text = element_text(size = 10))
                                            )
                    )+
  labs(title = "Median Family Income by Tract",
      subtitle = "Charlottesville",
      caption = source_acs <- "Data Source: American Community Survey, 2022") +
  theme_map() +
  theme(legend.position="right")


cville_ssw_map <- ssw_tract %>%
  filter(locality == "Charlottesville City") %>%
  filter(ssw_group == "below") %>%
  mutate(text = paste0(round(percent,0), "%")) %>%
  ggplot() +
  annotation_map_tile(zoomin = 1, progress = "none", cachedir = "../data/tempdata/") +
  geom_sf(aes(fill = percent), color = "white") +
  geom_sf_text(aes(label = text), size = 2.5, color = "black") +
  scale_fill_stepsn(colors = pal_ssw,
                    labels = scales::label_percent(scale = 1),
                    breaks = c(5,7,15,20,40,60),
                    trans = "log",
                    limits = c(min_ssw, max_ssw),
                    guide = guide_colourbar(title = "Percent Below SSS",
                                            title.position = "top",
                                            direction = "vertical",
                                            theme = theme(legend.key.height  = unit(10, "lines"),
                                                          legend.key.width = unit(0.5, "lines"),
                                                          text = element_text(size = 10)) 
                                            )
                    )+
  labs(title = "Families with Income below Self Sufficiency Standard",
      subtitle = "Charlottesville",
      caption = "") +
  theme_map()+
  theme(legend.position="right")

cville_inc_map 

cville_ssw_map
```

## Fluvanna County
```{r, echo=FALSE}
# Set name
local_name <- "Fluvanna County"

<<locality_summary>>

```

`r section_summary`

```{r ssw_table_flu}
# County self sufficiency table ----
selfsuff_table_flu <- selfsuff_table %>% 
  filter(county == "Fluvanna County")

selfsuff_table_flu %>% 
  select(-c(county)) %>% 
  gt(rowname_col = "name") %>% 
  # tab_row_group(label = "Deductions",
  #               rows = 8:10) %>% 
  # tab_row_group(label = "Costs",
  #               rows = 1:7) %>% 
  fmt_currency(
    columns = 2:3,
    currency = currency(
      html = "&#36;",
      default = "$"
    ),
    decimals = 2
  ) %>% 
  tab_style(
    style = list(
      cell_fill(color = "#F6D2A9"),
      cell_text(weight = "bold")
    ),
    locations = list(cells_body(rows = 11), cells_stub(rows = 11))
  ) %>% 
  tab_style(
    style = cell_text(align = "center", v_align = "middle"),
    locations = list(cells_column_labels(), cells_body())
  ) %>% 
  tab_style(
    style = cell_text(weight = "bold"),
    locations = list(cells_column_labels())
  ) %>% 
  tab_header(
    title = paste0(ssw_table_title, str_to_title(unique(selfsuff_table_flu$county)))
  ) %>% 
  tab_source_note(
    source_note = uw_sss_source
  )
  
```

```{r, echo = FALSE,fig.width=6, fig.height=5}
# Families with income below 35k, between 35k-self sufficiency wage & above ssw ----
fam_ssw_flu <- fam_ssw_dat %>% 
  filter(locality == "Fluvanna County, Virginia" & group != "Hispanic Families")

fam_ssw_flu %>% 
  arrange(desc(name)) %>% 
  ggplot(aes(x = group, y = value, group = group, fill = name, 
             label = text)) +
  geom_bar(stat = "identity", color = "white") + 
  geom_text(size = 3, position = position_stack(vjust = 0.5), lineheight = 1) +
  scale_fill_manual(values = fam_ssw_pal) +
  scale_x_discrete(name = "") +
  scale_y_continuous(labels = label_percent(scale = 1),
                     name = "") +
  guides(fill = guide_legend(reverse = TRUE)) +
  labs(title = fam_ssw_title, 
       subtitle = unique(fam_ssw_flu$locality_label),
       caption = source_acs) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        panel.grid.major.x = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position= "plot",
        plot.caption.position = "plot")
```

```{r, echo=FALSE,fig.width=6.5, fig.height=4}
# # Income distribution by race/ethnicity by county ----
# faminc_flu <- faminc_data %>% 
#   filter(locality == "Fluvanna County, Virginia" & group != "Hispanic Families")
# 
# faminc_flu %>% 
#   arrange(inc_rank) %>%
#   ggplot(aes(x = group, y = percent, group = group, fill = inc_band_group, 
#                label = text)) +
#   geom_bar(stat = "identity", color = "white") + 
#   geom_text(size = 3, position = position_stack(vjust = 0.5)) +
#   scale_fill_manual(values = faminc_pal) +
#   scale_x_discrete(name = "") +
#   scale_y_continuous(labels = label_percent(scale = 1),
#                      name = "") +
#   guides(fill = guide_legend(reverse = TRUE)) +
#   coord_flip() + 
#   labs(title = faminc_title, 
#        subtitle = unique(faminc_flu$locality_label),
#        caption = source_acs) +
#   theme_minimal() +
#   theme(legend.title=element_blank(),
#         legend.position = "top",
#         legend.location = "plot",
#         legend.justification="center",
#           panel.grid.major.x = element_blank(),
#           axis.ticks = element_blank(),
#           panel.grid.minor = element_blank(),
#           plot.title.position= "plot",
#           plot.caption.position = "plot")

```

```{r, echo=FALSE, warning = FALSE, message = FALSE, fig.width=12, fig.height=6}
# Geospatial visualization: Fluvanna County ----
fluv_inc_map <- med_faminc_tract %>%
  filter(locality == "Fluvanna County") %>%
  mutate(text = paste0("$", prettyNum(estimate, big.mark=",", preserve.width="none"))) %>%
  ggplot() +
  annotation_map_tile(zoomin = 1, progress = "none", cachedir = "../data/tempdata/") +
  geom_sf(aes(fill = estimate), color = "white") +
  geom_sf_text(aes(label = text), size = 2.5, color = "black") +
  scale_fill_stepsn(colors = rev(pal_inc),labels = scales::label_currency(scale = 1), 
                    trans = "log",
                    n.breaks = 7,
                    limits = c(min_inc, max_inc),
                    guide = guide_colourbar(title = "Median Family Income",
                                            title.position = "top",
                                            direction = "vertical",
                                            theme = theme(legend.key.height  = unit(10, "lines"),
                                                          legend.key.width = unit(0.5, "lines"),
                                                          text = element_text(size = 10))
                                            )
                    )+
  labs(title = "Median Family Income by Tract",
      subtitle = "Fluvanna County",
      caption = source_acs <- "Data Source: American Community Survey, 2022") +
  theme_map() +
  theme(legend.position="right")


fluv_ssw_map <- ssw_tract %>%
  filter(locality == "Fluvanna County") %>%
  filter(ssw_group == "below") %>%
  mutate(text = paste0(round(percent,0), "%")) %>%
  ggplot() +
  annotation_map_tile(zoomin = 1, progress = "none", cachedir = "../data/tempdata/") +
  geom_sf(aes(fill = percent), color = "white") +
  geom_sf_text(aes(label = text), size = 2.5, color = "black") +
  scale_fill_stepsn(colors = pal_ssw,
                    labels = scales::label_percent(scale = 1),
                    breaks = c(5,7,15,20,40,60),
                    trans = "log",
                    limits = c(min_ssw, max_ssw),
                    guide = guide_colourbar(title = "Percent Below SSS",
                                            title.position = "top",
                                            direction = "vertical",
                                            theme = theme(legend.key.height  = unit(10, "lines"),
                                                          legend.key.width = unit(0.5, "lines"),
                                                          text = element_text(size = 10)) 
                                            )
                    )+
  labs(title = "Families with Income below Self Sufficiency Standard",
      subtitle = "Fluvanna County",
      caption = "") +
  theme_map()+
  theme(legend.position="right")

fluv_inc_map 

fluv_ssw_map
```

## Greene County
```{r, echo=FALSE}
# Set name
local_name <- "Greene County"

<<locality_summary>>

```

`r section_summary`

```{r ssw_table_grn}
# County self sufficiency table ----
selfsuff_table_grn <- selfsuff_table %>% 
  filter(county == "Greene County")

selfsuff_table_grn %>% 
  select(-c(county)) %>% 
  gt(rowname_col = "name") %>% 
  # tab_row_group(label = "Deductions",
  #               rows = 8:10) %>% 
  # tab_row_group(label = "Costs",
  #               rows = 1:7) %>% 
  fmt_currency(
    columns = 2:3,
    currency = currency(
      html = "&#36;",
      default = "$"
    ),
    decimals = 2
  ) %>% 
  tab_style(
    style = list(
      cell_fill(color = "#F6D2A9"),
      cell_text(weight = "bold")
    ),
    locations = list(cells_body(rows = 11), cells_stub(rows = 11))
  ) %>% 
  tab_style(
    style = cell_text(align = "center", v_align = "middle"),
    locations = list(cells_column_labels(), cells_body())
  ) %>% 
  tab_style(
    style = cell_text(weight = "bold"),
    locations = list(cells_column_labels())
  ) %>% 
  tab_header(
    title = paste0(ssw_table_title, str_to_title(unique(selfsuff_table_grn$county)))
  ) %>% 
  tab_source_note(
    source_note = uw_sss_source
  )
  
```

```{r, echo = FALSE,fig.width=6, fig.height=5}
# Families with income below 35k, between 35k-self sufficiency wage & above ssw ----
fam_ssw_grn <- fam_ssw_dat %>% 
  filter(locality == "Greene County, Virginia" & group != "Hispanic Families")

fam_ssw_grn %>% 
  arrange(desc(name)) %>% 
  ggplot(aes(x = group, y = value, group = group, fill = name, 
             label = text)) +
  geom_bar(stat = "identity", color = "white") + 
  geom_text(size = 3, position = position_stack(vjust = 0.5), lineheight = 1) +
  scale_fill_manual(values = fam_ssw_pal) +
  scale_x_discrete(name = "") +
  scale_y_continuous(labels = label_percent(scale = 1),
                     name = "") +
  guides(fill = guide_legend(reverse = TRUE)) +
  labs(title = fam_ssw_title, 
       subtitle = unique(fam_ssw_grn$locality_label),
       caption = source_acs) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        panel.grid.major.x = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position= "plot",
        plot.caption.position = "plot")
```

```{r, echo=FALSE,fig.width=6.5, fig.height=4}
# # Income distribution by race/ethnicity by county ----
# faminc_grn <- faminc_data %>% 
#   filter(locality == "Greene County, Virginia" & group != "Hispanic Families")
# 
# faminc_grn %>% 
#   arrange(inc_rank) %>%
#   ggplot(aes(x = group, y = percent, group = group, fill = inc_band_group, 
#                label = text)) +
#   geom_bar(stat = "identity", color = "white") + 
#   geom_text(size = 3, position = position_stack(vjust = 0.5)) +
#   scale_fill_manual(values = faminc_pal) +
#   scale_x_discrete(name = "") +
#   scale_y_continuous(labels = label_percent(scale = 1),
#                      name = "") +
#   guides(fill = guide_legend(reverse = TRUE)) +
#   coord_flip() + 
#   labs(title = faminc_title, 
#        subtitle = unique(faminc_grn$locality_label),
#        caption = source_acs) +
#   theme_minimal() +
#   theme(legend.title=element_blank(),
#         legend.position = "top",
#         legend.location = "plot",
#         legend.justification="center",
#           panel.grid.major.x = element_blank(),
#           axis.ticks = element_blank(),
#           panel.grid.minor = element_blank(),
#           plot.title.position= "plot",
#           plot.caption.position = "plot")

```

```{r, echo=FALSE, warning = FALSE, message = FALSE, fig.width=12, fig.height=6}
# Geospatial visualization: Greene County ----
greene_inc_map <- med_faminc_tract %>%
  filter(locality == "Greene County") %>%
  mutate(text = paste0("$", prettyNum(estimate, big.mark=",", preserve.width="none"))) %>%
  ggplot() +
  annotation_map_tile(zoomin = 1, progress = "none", cachedir = "../data/tempdata/") +
  geom_sf(aes(fill = estimate), color = "white") +
  geom_sf_text(aes(label = text), size = 2.5, color = "black") +
  scale_fill_stepsn(colors = rev(pal_inc),
                    labels = scales::label_currency(scale = 1),
                    trans = "log",
                    n.breaks = 7,
                    limits = c(min_inc, max_inc),
                    guide = guide_colourbar(title = "Median Family Income",
                                            title.position = "top",
                                            direction = "vertical",
                                            theme = theme(legend.key.height  = unit(10, "lines"),
                                                          legend.key.width = unit(0.5, "lines"),
                                                          text = element_text(size = 10))
                                            )
                    )+
  labs(title = "Median Family Income by Tract",
      subtitle = "Greene County",
      caption = source_acs <- "Data Source: American Community Survey, 2022") +
  theme_map() +
  theme(legend.position="right")


greene_ssw_map <- ssw_tract %>%
  filter(locality == "Greene County") %>%
  filter(ssw_group == "below") %>%
  mutate(text = paste0(round(percent,0), "%")) %>%
  ggplot() +
  annotation_map_tile(zoomin = 1, progress = "none", cachedir = "../data/tempdata/") +
  geom_sf(aes(fill = percent), color = "white") +
  geom_sf_text(aes(label = text), size = 2.5, color = "black") +
  scale_fill_stepsn(colors = pal_ssw,
                    labels = scales::label_percent(scale = 1),
                    breaks = c(5,7,15,20,40,60),
                    trans = "log",
                    limits = c(min_ssw, max_ssw),
                    guide = guide_colourbar(title = "Percent Below SSS",
                                            title.position = "top",
                                            direction = "vertical",
                                            theme = theme(legend.key.height  = unit(10, "lines"),
                                                          legend.key.width = unit(0.5, "lines"),
                                                          text = element_text(size = 10)) 
                                            )
                    )+
  labs(title = "Families with Income below Self Sufficiency Standard",
      subtitle = "Greene County",
      caption = "") +
  theme_map()+
  theme(legend.position="right")

greene_inc_map

greene_ssw_map
```

## Louisa County
```{r, echo=FALSE}
# Set name
local_name <- "Louisa County"

<<locality_summary>>

```

`r section_summary`

```{r ssw_table_lou}
# County self sufficiency table ----
selfsuff_table_lou <- selfsuff_table %>% 
  filter(county == "Louisa County")

selfsuff_table_lou %>% 
  select(-c(county)) %>% 
  gt(rowname_col = "name") %>% 
  # tab_row_group(label = "Deductions",
  #               rows = 8:10) %>% 
  # tab_row_group(label = "Costs",
  #               rows = 1:7) %>% 
  fmt_currency(
    columns = 2:3,
    currency = currency(
      html = "&#36;",
      default = "$"
    ),
    decimals = 2
  ) %>% 
  tab_style(
    style = list(
      cell_fill(color = "#F6D2A9"),
      cell_text(weight = "bold")
    ),
    locations = list(cells_body(rows = 11), cells_stub(rows = 11))
  ) %>% 
  tab_style(
    style = cell_text(align = "center", v_align = "middle"),
    locations = list(cells_column_labels(), cells_body())
  ) %>% 
  tab_style(
    style = cell_text(weight = "bold"),
    locations = list(cells_column_labels())
  ) %>% 
  tab_header(
    title = paste0(ssw_table_title, str_to_title(unique(selfsuff_table_lou$county)))
  ) %>% 
  tab_source_note(
    source_note = uw_sss_source
  )
  
```

```{r, echo = FALSE,fig.width=6, fig.height=5}
# Families with income below 35k, between 35k-self sufficiency wage & above ssw ----
fam_ssw_lou <- fam_ssw_dat %>% 
  filter(locality == "Louisa County, Virginia" & group != "Hispanic Families")

fam_ssw_lou %>% 
  arrange(desc(name)) %>% 
  ggplot(aes(x = group, y = value, group = group, fill = name, 
             label = text)) +
  geom_bar(stat = "identity", color = "white") + 
  geom_text(size = 3, position = position_stack(vjust = 0.5), lineheight = 1) +
  scale_fill_manual(values = fam_ssw_pal) +
  scale_x_discrete(name = "") +
  scale_y_continuous(labels = label_percent(scale = 1),
                     name = "") +
  guides(fill = guide_legend(reverse = TRUE)) +
  labs(title = fam_ssw_title, 
       subtitle = unique(fam_ssw_lou$locality_label),
       caption = source_acs) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        panel.grid.major.x = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position= "plot",
        plot.caption.position = "plot")
```

```{r, echo=FALSE,fig.width=6.5, fig.height=4}
# # Income distribution by race/ethnicity by county ----
# faminc_lou <- faminc_data %>% 
#   filter(locality == "Louisa County, Virginia" & group != "Hispanic Families")
# 
# faminc_lou %>% 
#   arrange(inc_rank) %>%
#   ggplot(aes(x = group, y = percent, group = group, fill = inc_band_group, 
#                label = text)) +
#   geom_bar(stat = "identity", color = "white") + 
#   geom_text(size = 3, position = position_stack(vjust = 0.5)) +
#   scale_fill_manual(values = faminc_pal) +
#   scale_x_discrete(name = "") +
#   scale_y_continuous(labels = label_percent(scale = 1),
#                      name = "") +
#   guides(fill = guide_legend(reverse = TRUE)) +
#   coord_flip() + 
#   labs(title = faminc_title, 
#        subtitle = unique(faminc_lou$locality_label),
#        caption = source_acs) +
#   theme_minimal() +
#   theme(legend.title=element_blank(),
#         legend.position = "top",
#         legend.location = "plot",
#         legend.justification="center",
#           panel.grid.major.x = element_blank(),
#           axis.ticks = element_blank(),
#           panel.grid.minor = element_blank(),
#           plot.title.position= "plot",
#           plot.caption.position = "plot")

```

```{r, echo=FALSE, warning = FALSE, message = FALSE, fig.width=12, fig.height=6}
# Geospatial visualization: Louisa County ----
louisa_inc_map <- med_faminc_tract %>%
  filter(locality == "Louisa County") %>%
  mutate(text = paste0("$", prettyNum(estimate, big.mark=",", preserve.width="none"))) %>%
  ggplot() +
  annotation_map_tile(zoomin = 1, progress = "none", cachedir = "../data/tempdata/") +
  geom_sf(aes(fill = estimate), color = "white") +
  geom_sf_text(aes(label = text), size = 2.5, color = "black") +
  scale_fill_stepsn(colors = rev(pal_inc),
                    labels = scales::label_currency(scale = 1),
                    trans = "log",
                    n.breaks = 7,
                    limits = c(min_inc, max_inc),
                    guide = guide_colourbar(title = "Median Family Income",
                                            title.position = "top",
                                            direction = "vertical",
                                            theme = theme(legend.key.height  = unit(10, "lines"),
                                                          legend.key.width = unit(0.5, "lines"),
                                                          text = element_text(size = 10))
                                            )
                    )+
  labs(title = "Median Family Income by Tract",
      subtitle = "Louisa County",
      caption = source_acs <- "Data Source: American Community Survey, 2022") +
  theme_map() +
  theme(legend.position="right")


louisa_ssw_map <- ssw_tract %>%
  filter(locality == "Louisa County") %>%
  filter(ssw_group == "below") %>%
  mutate(text = paste0(round(percent,0), "%")) %>%
  ggplot() +
  annotation_map_tile(zoomin = 1, progress = "none", cachedir = "../data/tempdata/") +
  geom_sf(aes(fill = percent), color = "white") +
  geom_sf_text(aes(label = text), size = 2.5, color = "black") +
  scale_fill_stepsn(colors = pal_ssw,
                    labels = scales::label_percent(scale = 1),
                    breaks = c(5,7,15,20,40,60),
                    trans = "log",
                    limits = c(min_ssw, max_ssw),
                    guide = guide_colourbar(title = "Percent Below SSS",
                                            title.position = "top",
                                            direction = "vertical",
                                            theme = theme(legend.key.height  = unit(10, "lines"),
                                                          legend.key.width = unit(0.5, "lines"),
                                                          text = element_text(size = 10)) 
                                            )
                    )+
  labs(title = "Families with Income below Self Sufficiency Standard",
      subtitle = "Louisa County",
      caption = "") +
  theme_map()+
  theme(legend.position="right")

louisa_inc_map 

louisa_ssw_map
```

## Nelson County
```{r, echo=FALSE}
# Set name
local_name <- "Nelson County"

<<locality_summary>>

```

`r section_summary`

```{r ssw_table_nel}
# County self sufficiency table ----
selfsuff_table_nel <- selfsuff_table %>% 
  filter(county == "Nelson County")

selfsuff_table_nel %>% 
  select(-c(county)) %>% 
  gt(rowname_col = "name") %>% 
  # tab_row_group(label = "Deductions",
  #               rows = 8:10) %>% 
  # tab_row_group(label = "Costs",
  #               rows = 1:7) %>% 
  fmt_currency(
    columns = 2:3,
    currency = currency(
      html = "&#36;",
      default = "$"
    ),
    decimals = 2
  ) %>% 
  tab_style(
    style = list(
      cell_fill(color = "#F6D2A9"),
      cell_text(weight = "bold")
    ),
    locations = list(cells_body(rows = 11), cells_stub(rows = 11))
  ) %>% 
  tab_style(
    style = cell_text(align = "center", v_align = "middle"),
    locations = list(cells_column_labels(), cells_body())
  ) %>% 
  tab_style(
    style = cell_text(weight = "bold"),
    locations = list(cells_column_labels())
  ) %>% 
  tab_header(
    title = paste0(ssw_table_title, str_to_title(unique(selfsuff_table_nel$county)))
  ) %>% 
  tab_source_note(
    source_note = uw_sss_source
  )
  
```

```{r, echo = FALSE,fig.width=6, fig.height=5}
# Families with income below 35k, between 35k-self sufficiency wage & above ssw ----
fam_ssw_nel <- fam_ssw_dat %>% 
  filter(locality == "Nelson County, Virginia" & group != "Hispanic Families")

fam_ssw_nel %>% 
  arrange(desc(name)) %>% 
  ggplot(aes(x = group, y = value, group = group, fill = name, 
             label = text)) +
  geom_bar(stat = "identity", color = "white") + 
  geom_text(size = 3, position = position_stack(vjust = 0.5), lineheight = 1) +
  scale_fill_manual(values = fam_ssw_pal) +
  scale_x_discrete(name = "") +
  scale_y_continuous(labels = label_percent(scale = 1),
                     name = "") +
  guides(fill = guide_legend(reverse = TRUE)) +
  labs(title = fam_ssw_title, 
       subtitle = unique(fam_ssw_nel$locality_label),
       caption = source_acs) +
  theme_minimal() +
  theme(legend.title=element_blank(),
        legend.position = "top",
        panel.grid.major.x = element_blank(),
        axis.ticks = element_blank(),
        panel.grid.minor = element_blank(),
        plot.title.position= "plot",
        plot.caption.position = "plot")
```

```{r, echo=FALSE,fig.width=6.5, fig.height=4}
# # Income distribution by race/ethnicity by county ----
# faminc_nel <- faminc_data %>% 
#   filter(locality == "Nelson County, Virginia" & group != "Hispanic Families")
# 
# faminc_nel %>% 
#   arrange(inc_rank) %>%
#   ggplot(aes(x = group, y = percent, group = group, fill = inc_band_group, 
#                label = text)) +
#   geom_bar(stat = "identity", color = "white") + 
#   geom_text(size = 3, position = position_stack(vjust = 0.5)) +
#   scale_fill_manual(values = faminc_pal) +
#   scale_x_discrete(name = "") +
#   scale_y_continuous(labels = label_percent(scale = 1),
#                      name = "") +
#   guides(fill = guide_legend(reverse = TRUE)) +
#   coord_flip() + 
#   labs(title = faminc_title, 
#        subtitle = unique(faminc_nel$locality_label),
#        caption = source_acs) +
#   theme_minimal() +
#   theme(legend.title=element_blank(),
#         legend.position = "top",
#         legend.location = "plot",
#         legend.justification="center",
#           panel.grid.major.x = element_blank(),
#           axis.ticks = element_blank(),
#           panel.grid.minor = element_blank(),
#           plot.title.position= "plot",
#           plot.caption.position = "plot")

```

```{r, echo=FALSE, warning = FALSE, message = FALSE, fig.width=12, fig.height=6}
# Geospatial visualization: Nelson County ----
nels_inc_map <- med_faminc_tract %>%
  filter(locality == "Nelson County") %>%
  mutate(text = paste0("$", prettyNum(estimate, big.mark=",", preserve.width="none"))) %>%
  ggplot() +
  annotation_map_tile(zoomin = 1, progress = "none", cachedir = "../data/tempdata/") +
  geom_sf(aes(fill = estimate), color = "white") +
  geom_sf_text(aes(label = text), size = 2.5, color = "black") +
  scale_fill_stepsn(colors = rev(pal_inc),
                    labels = scales::label_currency(scale = 1),
                    trans = "log",
                    n.breaks = 7,
                    limits = c(min_inc, max_inc),
                    guide = guide_colourbar(title = "Median Family Income",
                                            title.position = "top",
                                            direction = "vertical",
                                            theme = theme(legend.key.height  = unit(10, "lines"),
                                                          legend.key.width = unit(0.5, "lines"),
                                                          text = element_text(size = 10))
                                            )
                    )+
  labs(title = "Median Family Income by Tract",
      subtitle = "Nelson County",
      caption = source_acs <- "Data Source: American Community Survey, 2022") +
  theme_map() +
  theme(legend.position="right")


nels_ssw_map <- ssw_tract %>%
  filter(locality == "Nelson County") %>%
  filter(ssw_group == "below") %>%
  mutate(text = paste0(round(percent,0), "%")) %>%
  ggplot() +
  annotation_map_tile(zoomin = 1, progress = "none", cachedir = "../data/tempdata/") +
  geom_sf(aes(fill = percent), color = "white") +
  geom_sf_text(aes(label = text), size = 2.5, color = "black") +
  scale_fill_stepsn(colors = pal_ssw,
                    labels = scales::label_percent(scale = 1),
                    breaks = c(5,7,15,20,40,60),
                    trans = "log",
                    limits = c(min_ssw, max_ssw),
                    guide = guide_colourbar(title = "Percent Below SSS",
                                            title.position = "top",
                                            direction = "vertical",
                                            theme = theme(legend.key.height  = unit(10, "lines"),
                                                          legend.key.width = unit(0.5, "lines"),
                                                          text = element_text(size = 10)) 
                                            )
                    )+
  labs(title = "Families with Income below Self Sufficiency Standard",
      subtitle = "Nelson County",
      caption = "") +
  theme_map()+
  theme(legend.position="right")

nels_inc_map

nels_ssw_map
```